### PR TITLE
Uniform command prompt

### PR DESCRIPTION
**Pull request by ranasheel2000**
This commit adds uniform command prompt.

**What this PR does / why we need it**:
This PR updates prompt as $ for uniformity with a little bit of explanation.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None.

**Special notes for your reviewer**:
None.
**Release note**:
None.

### CODE REVIEW

**Comment by liu-sheng** [comment]
AFAIK, it can not trigger CI if we comment multiple */test xxx* statements at same time.

**Comment by dims** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance
/override openlab/cloud-provider-openstack-acceptance-test-flexvolume-cinder
/override openlab/cloud-provider-openstack-acceptance-test-k8s-cinder
/override openlab/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization
/override openlab/cloud-provider-openstack-acceptance-test-lb-octavia
/override openlab/cloud-provider-openstack-acceptance-test-standalone-cinder

**Pull request merged**
