### PR TITLE
Add me (jichenjc) into reviewer

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
add as reviewer should be ok ? (Just +1/-1 ?)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrhillsman** [comment]
@dims @kiwik @hogepodge we should avoid running the full suite of jobs for changes to OWNERS file, are there any other file/dir change(s) that should be ignored?

**Comment by adisky** [comment]
@mrhillsman I think we can avoid /doc too

**Pull request merged**
