### PR TITLE
[occm] improve LB logic maintainability

### LINKED ISSUE #2374: [occm] improve LB logic maintainability
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

it's hard to maintain the `pkg/openstack/loadbalancer.go` file, since it contains more than 2.5k lines of code and some functions/methods are hard to read.

**What you expected to happen**:

I'm planning to split `pkg/openstack/loadbalancer.go` into multiple ``pkg/openstack/loadbalancer_*.go` files and simplify some complex func/method logic, e.g. remove a number if/then/elseif/else conditions, which complicate the code reading and maintainability.

**How to reproduce it**:

n/a

**Anything else we need to know?**:

n/a

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

This PR improves the loadbalancer code readability and maintainability.

**Which issue this PR fixes(if applicable)**:

fixes #2374

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dulek** [comment]
Oh my. Please put updating the license header into a separate PR, this one will be hard enough to review already.

**Comment by pierreprinetti** [comment]
@kayrus 
WRT changing the year of publication in the copyright header: what is your reasoning behind that?

**Comment by kayrus** [comment]
> WRT changing the year of publication in the copyright header: what is your reasoning behind that?

@pierreprinetti  My goal was to split `loadbalancer.go` into multiple files, and I noticed that I also need to put a new licence header there with a new 2023 year. In addition I looked into other places, where the headers are used. Nevertheless, this PR is a WIP. I'll focus on it a bit later and will move out the license update from it.

**Comment by pierreprinetti** [comment]
> I noticed that I also need to put a new license header there with a new 2023 year

Why?
Unless I'm mistaken, the copyright year means "year of first publication". Even if the content is moved around, and even if it is changed (or added to), I believe that the year of first publication has no reason to change.

That being said, the copyright year is not very interesting from a legal perspective, because the date of publication is also kept by Github. So you could probably put bananas in it.

**Comment by kayrus** [comment]
> Why?

@pierreprinetti I've seen such updates in other opensource projects. If you think that this doesn't make sense, then I'll put this year to the new files and skip others.

**Comment by dulek** [comment]
@kayrus: Hi! Do we have another attempt at merging this? I believe it's a very good idea to split this code into separate files.

**Pull request closed without merging**
