### PR TITLE
[OCCM]refactory code to prepare instance V2 implementation

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
instanceV2 need those functions, to avoid write stuffs in 2 different functions
consolidate them and use one path for both v1/v2
**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
my env is broken 

https://github.com/kubernetes/test-infra/pull/25487/files#diff-0a10db737194496c581cd20559817f87c4af2e3de38d8634deaeb7be4d36d483R62

I think we should update https://github.com/kubernetes/test-infra/pull/25487/files#diff-0a10db737194496c581cd20559817f87c4af2e3de38d8634deaeb7be4d36d483R62
 to ci-occm-e2e.sh 

per https://github.com/kubernetes/cloud-provider-openstack/tree/master/tests

will submit a PR when env restore back @ramineni @lingxiankong

**Comment by ramineni** [comment]
> my env is broken
> 
> https://github.com/kubernetes/test-infra/pull/25487/files#diff-0a10db737194496c581cd20559817f87c4af2e3de38d8634deaeb7be4d36d483R62
> 
> I think we should update https://github.com/kubernetes/test-infra/pull/25487/files#diff-0a10db737194496c581cd20559817f87c4af2e3de38d8634deaeb7be4d36d483R62 to ci-occm-e2e.sh
> 
> per https://github.com/kubernetes/cloud-provider-openstack/tree/master/tests
> 
> will submit a PR when env restore back @ramineni @lingxiankong

@jichenjc that file is being added as part of https://github.com/kubernetes/cloud-provider-openstack/pull/1803 . But Im seeing some gate failures, which needs debug , thats the reason PR is not merged yet.

**Comment by jichenjc** [comment]
>>thats the reason PR is not merged yet.

weird the gate is having issue now, need check again

**Comment by ramineni** [comment]
Its e2e-conformance test, which needs to be override until the PR is merged. Will look into it soon.

/override openstack-cloud-controller-manager-e2e-conformance-test

**Comment by jichenjc** [comment]
ok, I got it , "./tests/ci-occm-e2e-conformance.sh" is added into test-infra but not inside this repo now..

**Comment by lingxiankong** [comment]
/override openstack-cloud-controller-manager-e2e-conformance-test

**Pull request merged**
