### PR TITLE
trivial: Add manila-csi-plugin to .gitignore

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
Add manila-csi-plugin binary to gitignore

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```
`NONE`

### CODE REVIEW

**Comment by wangxiyuan** [comment]
It seems working now: https://github.com/kubernetes/cloud-provider-openstack/pull/687

**Comment by ramineni** [comment]
> It seems working now: #687

@wangxiyuan Thanks. What was the issue?

**Pull request merged**
