### PR TITLE
Remove cinder orphaned code / volume code deduplication

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

This PR removes orphaned code, which was migrated from in-tree k8s cloud providers. This is a follow-up for the https://github.com/kubernetes/cloud-provider-openstack/pull/808/files#r341504413 comment.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Since there is still code, which depends on CCM, the overall PR requires similar amount of time (maybe more) like in #735

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/849)

### CODE REVIEW

**Comment by adisky** [comment]
/ok-to-test
@kayrus please apply for k8s org membership

**Comment by adisky** [comment]
cc @dims @lingxiankong

**Comment by kayrus** [comment]
@lingxiankong @ramineni I need more time for this PR, since the cinder-related functionality contains a lot of duplicate code. Considering the amount of interfaces, it is not obvious what depends on what.

**Comment by ramineni** [comment]
> @lingxiankong @ramineni I need more time for this PR, since the cinder-related functionality contains a lot of duplicate code. Considering the amount of interfaces, it is not obvious what depends on what.

sure, let me know if you need any help

**Comment by kayrus** [comment]
@ramineni @lingxiankong ready for review

**Comment by ramineni** [comment]
@kayrus standalone cinder driver is deprecated in last cycle , lets wait for 1-2 cycles before its removal

**Comment by kayrus** [comment]
@ramineni I didn't touch standalone driver. It is compiled correctly, check it by running `make cinder-provisioner`. I removed legacy code, which is not used anywhere.

**Comment by ramineni** [comment]
> @ramineni I didn't touch standalone driver. It is compiled correctly, check it by running `make cinder-provisioner`. I removed legacy code, which is not used anywhere, but adds a lot of confusion to new contributors.

Thanks, got it. One more question,
Looks like openstack_routes_test.go is being deleted when corresponding openstack_routes.go still exists, why is that?

**Comment by ramineni** [comment]
@kayrus Interested to get it updated?

**Comment by kayrus** [comment]
@ramineni yes, a little bit later.

**Comment by ramineni** [comment]
/close
some of this is fixed in https://github.com/kubernetes/cloud-provider-openstack/pull/1036 , please repopen if you would like to work on this further.

**Pull request closed without merging**
