### PR TITLE
Adds url to log new bug in contributing.md

### PR DESCRIPTION
**Pull request by ranasheel2000**
This commit adds URL for logging new issues related to
cloud-provider-openstack.

**What this PR does / why we need it**:
This PR adds URL for logging new issue in this repository.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None.
**Special notes for your reviewer**:
None.
**Release note**:
None

### CODE REVIEW

**Comment by ranasheel2000** [comment]
I signed it

**Comment by NickrenREN** [comment]
thanks for this @ranasheel2000 
/lgtm
/approve

**Comment by ranasheel2000** [comment]
Thank you @NickrenREN for reviewing!!

**Pull request merged**
