### PR TITLE
[manila-csi-plugin] allow to update volumesnapshotcontents/status

### LINKED ISSUE #1142: [manila-csi-plugin] Snapshot creation failed because of insufficient permissions
> /kind bug

**What happened**:
When creating a manila snapshot, we got the following message about missing permissions: 
I0520 00:27:19.431196       1 snapshot_controller.go:200] updating VolumeSnapshotContent[snapcontent-a93535d3-000c-45c2-b1da-a19bb7b3f12d] error status failed volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-a93535d3-000c-45c2-b1da-a19bb7b3f12d" is forbidden: User "system:serviceaccount:manila-csi:openstack-manila-csi-controllerplugin" cannot update resource "volumesnapshotcontents/status" in API group "snapshot.storage.k8s.io" at the cluster scope

**What you expected to happen**:
Serviceaccount openstack-manila-csi-controllerplugin has the permission.

**How to reproduce it**:
1. Install manila csi plugin using helm charts
2. Create volumesnapshotclass
2. Create volumesnapshot

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:
This commit adds a permission that allows the controllerplugin to update volumesnapshotcontents/status.

**Which issue this PR fixes(if applicable)**:
fixes #1142 

```release-note
NONE
```

### CODE REVIEW

**Comment by gman0** [comment]
These RBAC rules are only needed for csi-snapshotter v2, and we haven't made the move yet - [snapshots created in v1 are incompatible with v2](https://github.com/kubernetes-csi/external-snapshotter#upgrade-from-v1alpha1-to-v1beta1). I've tested this without installing csi-snapshotter v2 and no errors were reported so I'm guessing this is fine. Since we'll need to upgrade to v2 eventually I'm ok with this change.

/lgtm
/approve

**Comment by gman0** [comment]
CC @ramineni

**Comment by ramineni** [comment]
@Fedosin @gman0 Have added questions on the issue https://github.com/kubernetes/cloud-provider-openstack/issues/1142
Ideally with current snapshotter version , this change shouldn't be required.
Lets continue discussion on the issue. Keeping this on hold till then
/hold

**Comment by ramineni** [comment]
/close 
no update , pls reopen if required

**Pull request closed without merging**
