### PR TITLE
[occm] remove instances v1 support

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

This is a code cleanup. The instances v1 cloud controller API support is removed. Instance address logic was moved to a separate `pkg/openstack/instances_addresses.go` file. The `pkg/openstack/instancesv2.go` was renamed to `pkg/openstack/instances.go`. Added context awareness to instances related functions and methods. Added a `SplitTrim` util function to extract comma-separated values from a string without a `strings.TrimSpace` call.

**Which issue this PR fixes(if applicable)**:

n/a

**Special notes for reviewers**:

**Release note**:

```release-note
[occm] remove instances v1 support
```

### CODE REVIEW

**Comment by kayrus** [comment]
@zetaab @dulek @jichenjc ready for review

**Review by zetaab — APPROVED** [review]
/approve

**Comment by kayrus** [comment]
@zetaab @dulek @jichenjc kindly ping with lgtm

**Pull request merged**
