### PR TITLE
[cinder-csi-plugin] Cleanup Mount package

### PR DESCRIPTION
**Pull request by ramineni**
**The binaries affected**:

IMPORTANT: Please also add the binary name in the title, e.g.
`[openstack-cloud-controller-manager]: Add UDP protocol support`
unless the PR affects multiple binaries.

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What this PR does / why we need it**:
This PR is to use k8s.io/utils package whereever possible and remove the redundancy code.
It also, removes the duplicate code of mount package exists in the repo.

**Which issue this PR fixes**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/922)

### CODE REVIEW

**Comment by jichenjc** [comment]
seems the check error is valid, maybe need some further check..

**Comment by lingxiankong** [comment]
___
*[pkg/util/metadata/metadata.go, line 32 at r1](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/922#-M-fjAdIBvVDQeUuYg8O:-M-fjAdIBvVDQeUuYg8P:b-lwx01s) ([raw file](https://github.com/kubernetes/cloud-provider-openstack/blob/c9d1df556f4b9e1fd869195558dc8913281e0721/pkg/util/metadata/metadata.go#L32)):*
> ```Go
> 	"k8s.io/klog"
> 
> 	"k8s.io/cloud-provider-openstack/pkg/csi/cinder/mount"
> ```

How about we move csi/cinder/mount to util/mount?

**Comment by ramineni** [comment]
> _[pkg/util/metadata/metadata.go, line 32 at r1](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/922#-M-fjAdIBvVDQeUuYg8O:-M-fjAdIBvVDQeUuYg8P:b-lwx01s) ([raw file](https://github.com/kubernetes/cloud-provider-openstack/blob/c9d1df556f4b9e1fd869195558dc8913281e0721/pkg/util/metadata/metadata.go#L32)):_
> 
> > ```go
> > 	"k8s.io/klog"
> > 
> > 	"k8s.io/cloud-provider-openstack/pkg/csi/cinder/mount"
> > ```
> 
> How about we move csi/cinder/mount to util/mount?

+1, i'm planning to move existing csi/cinder/mount to util package. Looks like there are some dependencies which needs to be addressed , so I thought of adding it as followup PR once this is merged. Is it fine?

**Comment by lingxiankong** [comment]
> +1, i'm planning to move existing csi/cinder/mount to util package. Looks like there are some dependencies which needs to be addressed , so I thought of adding it as followup PR once this is merged. Is it fine?

Sounds good. 

/lgtm

**Comment by ramineni** [comment]
cc @chrigl

**Pull request merged**
