### PR TITLE
Update Cinder CSI Driver Name

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
It updates cinder csi driver name in domain name notation format, as suggested (not enforced )by CSI specs.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
 `NONE`.

```release-note
```

### CODE REVIEW

**Comment by mrhillsman** [comment]
Issue appears to be related to Neutron, checking with the project now.

**Comment by dims** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-flexvolume-cinder

**Pull request merged**
