### PR TITLE
Revert "Disable test-lb-octavia openlab job"

### PR DESCRIPTION
**Pull request by dims**
Thanks to Mohammed Naser <mnaser@vexxhost.com>

This reverts commit c4027dc07560fa5f460566d4a154bcf1beb5dc60.

### CODE REVIEW

**Comment by liu-sheng** [comment]
not sure why VMs in vexxhost cannot request metadata from 169.254.169.254, which problem cause many jobs failed.

**Comment by mnaser** [comment]
Hey,

Where do you see traces of the metadata service not responding?  The VMs would never go up if the metadata service wasn’t responding, I believe. 

I don’t think these tests depend on the metadata service, or do they 

Thanks,
Mohammed

**Comment by mnaser** [comment]
I just checked this morning and I don't see any issues in a VM that I created

Please let me know if you have any more info

**Comment by mnaser** [comment]
OK, could be something tenant related, checking.

**Comment by mnaser** [comment]
Looks like the specific network had an issue, reloaded metadata and it's responding now.

**Comment by mrhillsman** [comment]
@liu-sheng @animationzl @kiwik lets move to using configdrive instead; we tested this quite a few times and it is intermittent, i cannot see a quicker way to resolve right now.

we can create another label/image with configdrive enabled and use it for these jobs only within VEXXHOST only - https://git.openstack.org/cgit/openstack-infra/project-config/tree/nodepool/nodepool.yaml#n41

**Comment by liu-sheng** [comment]
@mnaser @mrhillsman thanks for help, yes, now I have changed the job to use config driver at first, and will also try connecting with the metadata service as an alternative, see # theopenlab/openlab-zuul-jobs/pull/211

Thanks
Liu sheng

**Comment by dims** [comment]
/assign @flaper87 
/assign @dklyle 

Can one of you please lgtm?

**Pull request merged**
