### PR TITLE
[occm] update k8s.io/kubernetes to v1.29.0-rc.2 in go.mod

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

Update dependencies to 1.29.0-rc.2 and go version to 1.21.5
depends on #2487

**Which issue this PR fixes(if applicable)**:

n/a

**Special notes for reviewers**:

n/a

**Release note**:

```release-note
bump k8s dependencies and golang version, bump ubuntu version for test openstack VMs, add tests dmesg logs
```

### CODE REVIEW

**Comment by kayrus** [comment]
@dulek any idea why does this PR fail the tests?

**Comment by kayrus** [comment]
@dulek @zetaab basically the issue occurs because of the switching to the `debian-base:bookworm-v1.0.0` from the `debian-base:bullseye-v1.4.3` as a base image for docker images. `xfsprogs` has v6.1, which is incompatible with Ubuntu 20.04 5.4 kernel:

```
XFS (vdb): Superblock has unknown read-only compatible features (0x8) enabled.
XFS (vdb): Attempted to mount read-only compatible filesystem read-write.
XFS (vdb): Filesystem can only be safely mounted read only.
XFS (vdb): SB validate failed with error -22.
```

I'll revert the debian-base update, however I think it makes sense to keep the dmesg change and bump VM's ubuntu image from 20.04 to 22.04.

**Comment by kayrus** [comment]
cc @zetaab @jichenjc please approve as well

**Comment by jichenjc** [comment]
/lgtm

looks good ~, thanks

**Pull request merged**
