### PR TITLE
Update Ingress Resource API version

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
Ingress resources in extensions/v1beta1 are deprecated and will be
removed in v1.18, it is updated to  networking.k8s.io/v1beta1.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```
`NONE`

### CODE REVIEW

**Comment by lingxiankong** [comment]
/lgtm

@adisky we have the CI issue again?

**Comment by adisky** [comment]
> Build failed.
> 
> * [cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12 ](https://logs.openlabtesting.org/logs/58/658/52b21c7777aa096671ea5e86b2dfa247c00533ad/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12/ee4ec6a/) : POST_FAILURE in 15m 52s

@lingxiankong yes this test should no run

**Comment by adisky** [comment]
cc @mrhillsman @kiwik

**Comment by ramineni** [comment]
@adisky this test is not running on other patches, so may be retest should fix .. eg: https://github.com/kubernetes/cloud-provider-openstack/pull/657 , but we might have diff issue as we are seeing POST_FAILURE again on 1.15 e2e conformance jobs

**Comment by adisky** [comment]
@ramineni Thanks for the info
/retest

**Pull request merged**
