### PR TITLE
[cinder-csi-plugin] add Helm chart

### LINKED ISSUE #1010: [cinder-csi-plugin] Add helm chart for cinder-csi
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

As suggested in #65 and as the magnum uses Helm for a variety of deployments (Prometheus, NGINX Ingress ..)

### PR DESCRIPTION
**Pull request by tomaaron**
**What this PR does / why we need it**:
Adds a Helm chart for cinder-csi 
**Which issue this PR fixes(if applicable)**:
fixes #1010

**Special notes for reviewers**:

**Release note**:

```release-note
[cinder-csi-plugin] Helm chart is supported.
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
Thanks for your contribution. I have two suggestions:

1. Please create a folder on the top level (e.g. named `charts/cinder-csi-plugin`) and move all the files there.
1. Please add steps for how to use helm to install cinder-csi-plugin in https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md

**Comment by tomaaron** [comment]
Happy to contribute :) Let me know if you have any more suggestions.

**Comment by lingxiankong** [comment]
The job failure is http://dpaste.com/0RHF2MZ, I've already notified openlab team.

**Comment by lingxiankong** [comment]
I don't have another testing environment, so I haven't tested the chart, but I agree we could merge it and get feedback from users.

/lgtm

**Comment by ramineni** [comment]
@tomaaron Thanks for adding the support . couldnt get time to test it though . 
+1 to merge and get feedback to improvise further.

/lgtm

**Comment by tomaaron** [comment]
Thanks for approving. I'll be happy to improvise further after user feedback :)

**Pull request merged**
