### PR TITLE
[cinder-csi-plugin] Backward compatible to cinder api v2

### LINKED ISSUE #751: Cinder CSI plugin doesn't support cinder API v2
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Our Openstack provider provides only Cinder v1, v2 API.
I want use Cinder CSI plugin but I didn't find any information about minimal version. I found only https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/provider-configuration.md in which is v2 supported.

I tried apply plugin manifests with logs error result:
```
W0907 22:40:44.142809       1 main.go:120] Failed to GetOpenStackProvider: No suitable endpoint could be found in the service catalog.
```

I caught requested endpoint catalog returned from Openstack (some parts removed):
```json
{
    "token": {
        ...
        "catalog": [
            {
                "endpoints": [
                    {
                        "url": "http://openstack.homeatcloud.cz:8774/v2.1",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "07ff0cde3c69414ea6573e26f36ebc49"
                    },
                    {
                        "url": "http://10.1.100.30:8774/v2.1",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "722e90c57f934803a2c0a82b54de7a08"
                    },
                    {
                        "url": "http://10.1.100.30:8774/v2.1",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "fbc92fa02d6e4b3396bf21802a533ada"
                    }
                ],
                "type": "compute",
                "id": "0f7b6daf5c62484ca7eb155770c9542c",
                "name": "nova"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:9696/",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "54ca646055bb4cb0822626577eadc33f"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:9696/",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "af85c3827b634ab7b0b4d4a6315210c6"
                    },
                    {
                        "url": "http://10.1.100.30:9696/",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "e4e3239c148c4ecd8aa99b8061187f4d"
                    }
                ],
                "type": "network",
                "id": "1434cde89f6a4571ad6ce723ec5fcec6",
                "name": "neutron"
            },
            {
                "endpoints": [
                    {
                        "url": "http://openstack.homeatcloud.cz:9876/",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "391b06a0a77543b5a0e20c90f2636168"
                    },
                    {
                        "url": "http://10.1.100.30:9876/",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "484c5014a4a94064bf2d695a0f0e7ada"
                    },
                    {
                        "url": "http://10.1.100.30:9876/",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "d2e4dcd0f8214208b51f6f77919ad6a5"
                    }
                ],
                "type": "load-balancer",
                "id": "1d783eb37df24133909d72fa0924be21",
                "name": "octavia"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:9292",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "1868e1df0bdd4ed6bebb4fb5039bacde"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:9292",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "9d885c8e205847d28e8a1406ccc5e141"
                    },
                    {
                        "url": "http://10.1.100.30:9292",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "c976f1e73f664e06a6ad85a31bb8bdd0"
                    }
                ],
                "type": "image",
                "id": "21e43259e2eb4fa7a8262496782a23b3",
                "name": "glance"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:35357/v3",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "08cb65047c0d4f5696aa7d33d6c0b604"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:5000/v3",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "58835a4b59e9470a862f6d92fcdd9698"
                    },
                    {
                        "url": "http://10.1.100.30:5000/v3",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "72f044871b644a8daf7b2e62e854599e"
                    }
                ],
                "type": "identity",
                "id": "2d505aab3f0949bebb8dfc53af17082b",
                "name": "keystone3"
            },
            {
                "endpoints": [
                    {
                        "url": "http://openstack.homeatcloud.cz:8786/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "19c73fd3b8294f86ac891953e2eb0e0e"
                    },
                    {
                        "url": "http://10.1.100.30:8786/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "b693250c9c704e80874d2901a050eeb3"
                    },
                    {
                        "url": "http://10.1.100.30:8786/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "d420d2fe4725483cb6d8a2f14ec8eb08"
                    }
                ],
                "type": "share",
                "id": "379f6818e967485cb4d9e833edf04cc6",
                "name": "manila"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8786/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "6608b5a18f134604a76bbcd2e59ce5b9"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8786/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "b9a8cadf13574ca1b349684b865ab02d"
                    },
                    {
                        "url": "http://10.1.100.30:8786/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "ba82b239b30f4a468cb0b425c516cc76"
                    }
                ],
                "type": "sharev2",
                "id": "3b1e6b6753584d6087c0b85b2f565f9a",
                "name": "manilav2"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8004/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "4b68afd1b6934a81a61f49a29ce60c6e"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8004/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "7e5f8b7292a5477cb24b933d3fb19fa0"
                    },
                    {
                        "url": "http://10.1.100.30:8004/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "9d7f86d0c8b44dee9d8efe857442d834"
                    }
                ],
                "type": "orchestration",
                "id": "4d3f4f81304d4c36ba673c81c81b2a7b",
                "name": "heat"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8773/services/Cloud",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "9a26d9a7b48d4c8fb470d8b74ba6f610"
                    },
                    {
                        "url": "http://10.1.100.30:8773/services/Admin",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "c1c19128834c4e4cb655838ac4899a5a"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8773/services/Cloud",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "f1bb7b02ad5a40509b7196b43a7eb390"
                    }
                ],
                "type": "ec2",
                "id": "67c2eaba09c449b5a6a254a1d2960257",
                "name": "ec2"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8776/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "0e485338f9e4473f90e923c2a0324924"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8776/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "3387b678759c46d3a44365325ea3e806"
                    },
                    {
                        "url": "http://10.1.100.30:8776/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "524d86b275b74c56a2455e7ef966fe9f"
                    },
                    {
                        "url": "http://10.1.100.30:8776/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "a806e9c76b1942edb2a8fbc4b79e6df8"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8776/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "d4c777a8fe1d48a09f28cf57fede4e7a"
                    },
                    {
                        "url": "http://10.1.100.30:8776/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "f890a7eb440e425d9793151a0c61cca2"
                    }
                ],
                "type": "volumev2",
                "id": "86460378058646388e0733de2b01a4b9",
                "name": "cinderv2"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8776/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "0b6ed5538bb042a383bc29efd056f669"
                    },
                    {
                        "url": "http://10.1.100.30:8776/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "4d3a39b91fb745e69d1278509ef93baf"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8776/v1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "f27c9f5acf744584aa05bb099d342ee9"
                    }
                ],
                "type": "volume",
                "id": "96620b73fb934a019ef21dba9fc048b4",
                "name": "cinder"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8000/v1",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "5e7b33c3e790430a9056d1cd8c69a805"
                    },
                    {
                        "url": "http://10.1.100.30:8000/v1",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "6e3793d3e3b24f99989e903c54ee4ef1"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8000/v1",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "ebcb429903f74ed583d9a87cd89285d1"
                    }
                ],
                "type": "cloudformation",
                "id": "b45f05956a6c405aa7532b1cf42074be",
                "name": "heat-cfn"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8774/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "5c6448717ee7469d9298437bc88a4342"
                    },
                    {
                        "url": "http://10.1.100.30:8774/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "74acc1fb82a44d1d8224e7380b396c6b"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8774/v2/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "9bd0b0dd4913450288b18a6c58cfb7fb"
                    }
                ],
                "type": "compute_legacy",
                "id": "bbd2449b1c9b406bbd512ebc6e7150fc",
                "name": "nova20"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8386/v1.1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "3d1dad1f6bbc47999572c1dcf49f9c6f"
                    },
                    {
                        "url": "http://10.1.100.30:8386/v1.1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "87a31d8d450e443384c21b053547d1d4"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8386/v1.1/e8b2f1d108554d7484e2298f69c97f44",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "9e02fdc39dfc43ee8cc69409810cd653"
                    }
                ],
                "type": "data-processing",
                "id": "bfb19fa8dfb849b7bfe8f7c0c6b283b2",
                "name": "sahara"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:5000/v2.0",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "3f7077f845a049eea00ee377a2bd6e52"
                    },
                    {
                        "url": "http://10.1.100.30:35357/v2.0",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "586e5bbe74924c388dd856c551c880c6"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:5000/v2.0",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "6d9a5b6989ab444eb27e1386c18e014c"
                    }
                ],
                "type": "identity",
                "id": "c3f75fb329e9479d815f495d5aff9a03",
                "name": "keystone"
            },
            {
                "endpoints": [
                    {
                        "url": "http://10.1.100.30:8777",
                        "interface": "internal",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "9ebeff2e62f74e448c5c9c64c7b7d783"
                    },
                    {
                        "url": "http://openstack.homeatcloud.cz:8777",
                        "interface": "public",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "a3393ab9d6c34c2683b52053f63e1562"
                    },
                    {
                        "url": "http://10.1.100.30:8777",
                        "interface": "admin",
                        "region": "RegionOne",
                        "region_id": "RegionOne",
                        "id": "e7eb9aaaf3af4d01bc2c54b2120111ed"
                    }
                ],
                "type": "metering",
                "id": "f64e2863694145ebac24aa48d8481637",
                "name": "ceilometer"
            }
        ],
        ...
    }
}
```
I'm not proficient in Go language but I found only:
```go
	// Init Cinder ServiceClient
	blockstorageclient, err := openstack.NewBlockStorageV3(provider, epOpts)
```
in https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack.go.
Is it mean it support only v3? Will you support older v2? Or there is error elsewhere?

**What you expected to happen**:
Cinder CSI plugin supports cinder v2 API.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: v1.15
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by vincenthcui**
**What this PR does / why we need it**:

add backward compatible to Cinder API v2
Cinder API v2 is deprecated in official support,
but upgrade to v3 is hard work for old cloud platforms (We start at OS Mitaka version).

**Which issue this PR fixes(if applicable)**:
fixes #751 #1059 

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vincenthcui** [comment]
/assign @chrigl
Code has been tested on my local cluster, plz review this PR :)

**Comment by ramineni** [comment]
@vincenthcui I guess, some features would be broken if using v2 (like volume expansion etc) and as it wont be properly tested and will become unmaintained from community side
@lingxiankong @chrigl  how do we want to go about this? thoughts?

**Comment by jichenjc** [comment]
reasonable change, assume you might want to add more doc change 

the question I have is
1) https://docs.openstack.org/api-ref/block-storage/ indicated v2 is deprecated , seems it's a burden to maintain such things in CPO
2) we will not have CI test ,or is it possible to add one?

**Comment by vincenthcui** [comment]
> @vincenthcui I guess, some features would be broken if using v2 (like volume expansion etc) and as it wont be properly tested and will become unmaintained from community side
> @lingxiankong @chrigl how do we want to go about this? thoughts?

@ramineni cinder provisions is static and doesn't support resize, so I don't thinks expansion is really required by cinder-csi-plugin.

**Comment by vincenthcui** [comment]
If needed, I can maintain 

> reasonable change, assume you might want to add more doc change
> 
> the question I have is
> 
> 1. https://docs.openstack.org/api-ref/block-storage/ indicated v2 is deprecated , seems it's a burden to maintain such things in CPO
> 2. we will not have CI test ,or is it possible to add one?

1. I can maintain v2 version for a lot of times, more than one year (our cloud platform has no plan to do upgrade)
2. Yes, I'd like to. CI tests are more reliable than manual. I will try. Do you have some CI test guides or standards to follow?

**Comment by vincenthcui** [comment]
@chrigl is busy now, can you help to review this commit @lingxiankong

**Comment by vincenthcui** [comment]
> @vincenthcui I guess, some features would be broken if using v2 (like volume expansion etc) and as it wont be properly tested and will become unmaintained from community side
> @lingxiankong @chrigl how do we want to go about this? thoughts?

It's hard to inject test environment into csi openstack provider, it accept no arguments. More test needs change CreateOpenStackProvider interface first, but I think it's another issue.

**Comment by vincenthcui** [comment]
It took me a long time to merge this pr into master. And as @jichenjc said, compatible with a deprecated version  is a burden to maintain. So I decided to close this PR and using forked version in my local cluster. If anyone need backward compatible ability, just +1 and reopen this PR.

**Pull request closed without merging**
