### PR TITLE
[manila-csi-plugin] Bump sidecar versions for v1.22 release

### PR DESCRIPTION
**Pull request by gman0**
**What this PR does / why we need it**:

This PR updates sidecars for v1.22:

* csi-node-driver-registrar: v1.3.0 -> v2.2.0
* csi-provisioner: v2.0.2 -> v2.2.2
* csi-snapshotter: v2.1.3 -> v4.1.1

Also, removed `preStop` hook from node-driver-registrar container spec, as it's no longer needed: https://github.com/kubernetes-csi/node-driver-registrar/pull/61

**Special notes for reviewers**:

In the light of current issues with CPO's CI infra, I've run the acceptance manually and everything seems to remain working just fine.

**Release note**:

```release-note
[manila-csi-plugin] Updated sidecar versions: csi-node-driver-registrar v2.2.0, csi-provisioner v2.2.2, csi-snapshotter v4.1.1
```

### CODE REVIEW

**Comment by gman0** [comment]
PTAL @ramineni @gouthampacha @tombarron

**Comment by ramineni** [comment]
@gman0 As discussed, our CI is not up yet, please run all the relevant tests manually and post the success results.

**Comment by ramineni** [comment]
@gman0 Please update manifests as well https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/manila-csi-plugin/

**Comment by gman0** [comment]
@ramineni I've updated the manifests too. Testing was done as a part of https://github.com/kubernetes/cloud-provider-openstack/pull/1601#issuecomment-897656919

**Comment by gman0** [comment]
I think we're missing approval for this PR.

**Review by tombarron — APPROVED** [review]

**Comment by tombarron** [comment]
/lgtm
/approve

Files are outside /pkg/csi/manila so this is just for the record

**Comment by tombarron** [comment]
@ramineni seems like this is ready for approval?

**Comment by lingxiankong** [comment]
Given the current CI issue and the comments of the reviewers, I will manually merge this PR.

**Pull request merged**
