### PR TITLE
[octavia-ingress-controller] Add octavia.flavor-id option

### PR DESCRIPTION
**Pull request by Hugoch**
**What this PR does / why we need it**:
Adds a new `octavia.flavor-id` option. It uses the given flavor id to create the LB rather than auto-selecting the default. Especially useful for Openstack installations where multiple Octavia flavors exist.

**Special notes for reviewers**:
Add the flavor id of the load-balancer to be created in octavia-ingress-controller configuration
```
octavia:
    flavor-id: XXX
```

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Hugoch** [comment]
Blocked by test gate issue https://github.com/kubernetes/cloud-provider-openstack/issues/2083
@jichenjc is on it  (https://github.com/kubernetes/cloud-provider-openstack/pull/2084)

**Review by zetaab — APPROVED** [review]
/lgtm

**Comment by zetaab** [comment]
@Hugoch can you rebase this against master branch to get test fixes

**Comment by jichenjc** [comment]
/approve

could you please help provide an update to the KC later?

**Pull request merged**
