### PR TITLE
client-keystone-auth supports client certificates

### LINKED ISSUE #366: Support client certificate
/kind feature

Hello, when we have OpenStack endpoint with client certificate, we can't use `client-keystone-auth`.
I want `client-keystone-auth` support  `OS_CERT` and `OS_KEY` option like openstack cli.

### PR DESCRIPTION
**Pull request by takaishi**
**What this PR does / why we need it**: `client-keystone-auth` supports client certificate with `OS_CERT` and `OS_KEY` options.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #366

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by takaishi** [comment]
@k8s-ci-robot I signed CLA.

**Comment by dims** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance

**Pull request merged**
