### PR TITLE
[WIP] cleanup mount package

### PR DESCRIPTION
**Pull request by ramineni**
This commit reuses kubernetes/pkg/util/mount in places
required. And also removes, existing copy of k8s mount
package in repository.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by adisky** [comment]
@ramineni Please reopen it, when you restart working on it.
/close

**Comment by ramineni** [comment]
@adisky I'm waiting for block volume to be merged , to continue with this PR as both have related changes.

**Comment by adisky** [comment]
@ramineni you can remove WIP, as work is completed from your side.

**Comment by ramineni** [comment]
/close 
will propose new PR as needs more changes

**Pull request closed without merging**
