### PR TITLE
add cloud-provider-openstack-format job

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Add a new test to

* run gofmt checking
* checking normal typos

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Depends on theopenlab/openlab-zuul-jobs#200
/assign dims

**Release note**:

```release-note
add cloud-provider-openstack-format job
```

### CODE REVIEW

**Comment by dims** [comment]
@dixudx can you please address this comment? https://github.com/theopenlab/openlab-zuul-jobs/pull/200#discussion_r185769602

**Comment by dims** [comment]
@dixudx can't seem to trigger the tests, want to rebase?

**Comment by dixudx** [comment]
@dims Seems I forgot to add `cloud-provider-openstack-format` to pipeline, which is blocking this CI testing.

Filed theopenlab/openlab-zuul-jobs#210. PTAL. Thanks.

**Comment by dixudx** [comment]
> Last reconfigured: Tue May 08 2018 14:44:10 GMT+0800 (CST)

Seems the new pipeline has not been added.

Will wait until it's ready.

**Comment by dims** [comment]
@kiwik can you please ping us when this is ready?

**Comment by dims** [comment]
@kiwik @liu-sheng - there seems to problems with this new job. Can you please help make it go green?

**Comment by liu-sheng** [comment]
@dims @dixudx the format check job is OK now.

**Comment by dixudx** [comment]
@liu-sheng Thanks for your great help. Really appreciate.

**Comment by liu-sheng** [comment]
@dixudx welcome :)

**Comment by dims** [comment]
@liu-sheng nice! thanks

**Pull request merged**
