### PR TITLE
[manila-csi-plugin] Move to charts dir

### PR DESCRIPTION
**Pull request by strigazi**
To be able to release and browse all charts (two for now)
in a single place, move to charts.

related issue: #1066 
related pr: #1067

```release-note
NONE
```

### CODE REVIEW

**Comment by strigazi** [comment]
@lingxiankong I opened this PR to have the move self contained to trim down the work needed to release the charts. Let me know if this helps. If you prefer we can close this and wait for #1067

**Comment by lingxiankong** [comment]
> @lingxiankong I opened this PR to have the move self contained to trim down the work needed to release the charts. Let me know if this helps. If you prefer we can close this and wait for #1067

I agree we go for this approach.

**Comment by tombarron** [comment]
works with [pccket manilakube](https://github.com/tombarron/pocketmanilakube) if I update the helm chart location

**Comment by gman0** [comment]
This will break csi-manila's CI job. Here's a fix for that https://github.com/theopenlab/openlab-zuul-jobs/pull/910

**Comment by lingxiankong** [comment]
@gman0, you need to explicitly type `/approve` to allow this PR to be merged, I'll leave that for you :-)

**Comment by gman0** [comment]
@lingxiankong seems like somebody else will have to approve :P

**Comment by tombarron** [comment]
These won't have any effect but:
/lgtm
/approve

**Comment by tombarron** [comment]
Submitted [PR1111(https://github.com/kubernetes/cloud-provider-openstack/pull/1111) to set up an OWNERS file for manila-csi,

**Pull request merged**
