### PR TITLE
Add Adam Litke to the OWNERS file

### PR DESCRIPTION
**Pull request by aglitke**
Hi all.  I just noticed that the standalone-cinder provisioner that I've been maintaining in the kubernetes incubator has been copied over here.  Adding my name to the list of collaborators.

Signed-off-by: Adam Litke <alitke@redhat.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dims** [comment]
welcome! @aglitke 

/approve

**Comment by FengyunPan2** [comment]
welcome! @aglitke

**Pull request merged**
