### PR TITLE
[cinder-csi-plugin]: fix pagination, avoid unnecessary memory allocation, add more logs

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

This PR addresses a couple of findings from the #2295 
Improves memory allocation and adds extra logs helping to debug volume pagination issues.

**Release note**:

```release-note
Fixed pagination issue in Cinder CSI ListVolumes and ListSnapshots calls
```

### CODE REVIEW

**Comment by kayrus** [comment]
@jichenjc ready for review

**Comment by mdbooth** [comment]
> @jichenjc @mdbooth ready for review

I'm away for a few days, but don't let me be a roadblock. If you really want an extra set of eyes on it I should be able to review it by Wednesday.

**Pull request merged**
