### PR TITLE
Move loadbalancer annotation to service in README file

### LINKED ISSUE #346: Docs error in Loadbalancers example README.MD
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
use cloud-provider-openstack/examples/loadbalancers/internal-http-nginx.yaml to create **internal** loadbalancer failed, cloud-provider-openstack create a **external** loadbalancer.

**What you expected to happen**:
use cloud-provider-openstack/examples/loadbalancers/internal-http-nginx.yaml to create **INTERNAL** loadbalancer successfully.

**How to reproduce it (as minimally and precisely as possible)**:
when you run k8s and cloud-provider-openstack successful, run "kubectl create -f examples/loadbalancers/internal-http-nginx.yaml"

**REASON:**
the code in openstack_loadbalancer.go assume LB is external, it read service annotation "service.beta.kubernetes.io/openstack-internal-load-balancer" to create internal or external LB. But the internal-http-nginx.yaml and external-http-nginx.yaml use annotations in pos, not service, so the yaml file should be changed to below content.
`---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: internal-http-nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: internal-http-nginx-service
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80`

### PR DESCRIPTION
**Pull request by brtknr**
**What this PR does / why we need it**: The README is out of date compared to the yams file.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #346 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by chaosaffe** [comment]
Overriding test failure as this is a docs change and does not effect e2e-conformance
/override cloud-provider-openstack-acceptance-test-e2e-conformance 

Thanks @brtknr for your contribution!

**Comment by brtknr** [comment]
Closes https://github.com/kubernetes/cloud-provider-openstack/issues/346

**Comment by brtknr** [comment]
As you already pointed out earlier, this is a doc change only so doesn't require e2e test.

**Comment by chaosaffe** [comment]
@brtknr I don't have permission to override the failing test and the tests run on all PRs, my apologies for the inconvenience

**Pull request merged**
