### PR TITLE
Add ramineni as reviewer to OWNERS file

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
This PR is to add me as reviewer
My contributions : https://github.com/search?q=reviewed-by%3Aramineni+org%3Akubernetes+-author%3Aramineni
https://github.com/search?q=is%3Apr+author%3Aramineni+org%3Akubernetes 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by ramineni** [comment]
cc @dims @lingxiankong

**Comment by dims** [comment]
/approve

@hogepodge, other approvers ok with you?

Thanks,
Dims

**Pull request merged**
