### PR TITLE
initialize explictly to enable verbose option

### LINKED ISSUE #539: enable log
> /kind feature

**What happened**:
I have to debug communication between the pod and my openstack. I cannot pass -v4 or -v5 to the kubernetes manifest

```
# kubectl exec -it csi-provisioner-cinderplugin-0 -n kube-system -c cinder -- /bin/sh

sh-4.2# /bin/cinder-csi-plugin
Error: required flag(s) "cloud-config", "endpoint", "nodeid" not set
Usage:
  Cinder [flags]

Flags:
      --cloud-config string     CSI driver cloud config
      --cluster string          The identifier of the cluster that the plugin is running in.
      --endpoint string         CSI endpoint
  -h, --help                    help for Cinder
      --httptest.serve string   if non-empty, httptest.NewServer serves on this address and blocks
      --nodeid string           node id
```

**What you expected to happen**:
I expected that -v would be available in the flags

**How to reproduce it (as minimally and precisely as possible)**:
Just launch the manifest and check /bin/cinder-csi-plugin inside one of the pods

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #539 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dricoco** [comment]
Can we change the label of this issue for the pending test?

**Comment by jichenjc** [comment]
is this ongoing?

**Comment by dricoco** [comment]
What do you mean by ongoing ?

**Comment by jichenjc** [comment]
The title of this PR is wip: so I think it's work in progress?

**Comment by dricoco** [comment]
I don't get why there is wip in the title as this is only one line enabling debug in klog.
I don't see what extra work would be added in this merge request
@adisky have you an idea?

**Comment by dims** [comment]
/hold

need to look deeper, apparently openstack-cloud-controller-manager works but this binary fails, so we need to check what's different between the two. We are calling `klog.InitFlags` a few lines below that

**Comment by ramineni** [comment]
@dims updated the patch as discussed , PTAL

**Comment by dricoco** [comment]
Sorry This isn't working

I had to remove the init function and move   flag.Set("logtostderr", "true")

as first line in main() to have it work

**Pull request merged**
