### PR TITLE
[all] Update k/k dependency to v1.22.0

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
This PR updates the dependency to k/k 1.22.0

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ramineni** [comment]
@gman0 Could you please test manila plugins for v1.22 . Thanks

**Comment by gman0** [comment]
@ramineni for manila-csi:

1. checked-out the branch from this PR
2. `make image-manila-csi-plugin`
3. for deployment I actually used the helm chart from https://github.com/kubernetes/cloud-provider-openstack/pull/1618 , I modified `values.yaml` accordingly (img repo and tag).

What was tested:
* creating a volume
* creating a snapshot
* creating a volume from a snapshot
* expanding a volume
* cleaning up all created resources

```
$ kubectl get all | grep manila
pod/ss-openstack-manila-csi-controllerplugin-0     4/4     Running   0          4m44s
pod/ss-openstack-manila-csi-nodeplugin-wsfqn       2/2     Running   0          4m44s
service/ss-openstack-manila-csi-controllerplugin   ClusterIP   10.0.0.173   <none>        12345/TCP   4m44s
daemonset.apps/ss-openstack-manila-csi-nodeplugin   1         1         1       1            1           <none>          4m44s
statefulset.apps/ss-openstack-manila-csi-controllerplugin   1/1     4m45s

$  kubectl logs ss-openstack-manila-csi-controllerplugin-0 -c cephfs-nodeplugin
I0812 13:22:44.184954       1 driver.go:127] Driver: cephfs.manila.csi.openstack.org
I0812 13:22:44.185003       1 driver.go:128] Driver version: 0.9.0@8d384fbf
```

Provisioning CephFS PVC
```
$ kubectl create -f pvc.yaml
persistentvolumeclaim/new-cephfs-share-pvc created
$  kubectl get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
new-cephfs-share-pvc   Bound    pvc-196023a4-7a92-45b6-b7c0-5b45434a9e85   1Gi        RWX            devstack-cephfs   9s
$ openstack share list
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
| ID                                   | Name                                     | Size | Share Proto | Status    | Is Public | Share Type Name | Host                                 | Availability Zone |
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
| 359132b5-5d58-4fb2-a429-a75da62b33ac | pvc-196023a4-7a92-45b6-b7c0-5b45434a9e85 |    1 | CEPHFS      | available | False     | cephfstype      | rvasek-devstack@cephfsnative1#cephfs | manila-zone-0     |
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
```

Creating a snapshot:
```
$  kubectl create -f snapshotcreate.yaml 
volumesnapshot.snapshot.storage.k8s.io/new-cephfs-share-snap created
$  kubectl get volumesnapshot
NAME                    READYTOUSE   SOURCEPVC              SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS     SNAPSHOTCONTENT                                    CREATIONTIME   AGE
new-cephfs-share-snap   true         new-cephfs-share-pvc                           1Gi           devstack-cephfs   snapcontent-1cbf826c-b1df-483e-b7db-9f2e21bd3ad1   51s            51s
$ openstack share snapshot list
+--------------------------------------+-----------------------------------------------+
| ID                                   | Name                                          |
+--------------------------------------+-----------------------------------------------+
| a4ff6908-6747-466e-ba32-c68ed796ca00 | snapshot-1cbf826c-b1df-483e-b7db-9f2e21bd3ad1 |
+--------------------------------------+-----------------------------------------------+
```

Creating a PVC from snapshot:
```
$ kubectl create -f snapshotrestore.yaml 
persistentvolumeclaim/new-cephfs-share-snap-restore created
$ kubectl get pvc
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
new-cephfs-share-pvc            Bound    pvc-196023a4-7a92-45b6-b7c0-5b45434a9e85   1Gi        RWX            devstack-cephfs   8m46s
new-cephfs-share-snap-restore   Bound    pvc-72ede75a-1c65-416b-9065-d3139c63d9d2   1Gi        RWX            devstack-cephfs   2m25s
$ openstack share list
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
| ID                                   | Name                                     | Size | Share Proto | Status    | Is Public | Share Type Name | Host                                 | Availability Zone |
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
| 359132b5-5d58-4fb2-a429-a75da62b33ac | pvc-196023a4-7a92-45b6-b7c0-5b45434a9e85 |    1 | CEPHFS      | available | False     | cephfstype      | rvasek-devstack@cephfsnative1#cephfs | manila-zone-0     |
| 56c37f32-19a8-4f4b-9c3a-6a70d2e8fa49 | pvc-72ede75a-1c65-416b-9065-d3139c63d9d2 |    1 | CEPHFS      | available | False     | cephfstype      | rvasek-devstack@cephfsnative1#cephfs | manila-zone-0     |
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
```

Expanding PVC to 2GiB:
```
$ kubectl patch persistentvolumeclaim/new-cephfs-share-snap-restore -p '{"spec": {"resources": {"requests": {"storage": "2Gi"}}}}'
persistentvolumeclaim/new-cephfs-share-snap-restore patched
$ openstack share list
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
| ID                                   | Name                                     | Size | Share Proto | Status    | Is Public | Share Type Name | Host                                 | Availability Zone |
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
| 359132b5-5d58-4fb2-a429-a75da62b33ac | pvc-196023a4-7a92-45b6-b7c0-5b45434a9e85 |    1 | CEPHFS      | available | False     | cephfstype      | rvasek-devstack@cephfsnative1#cephfs | manila-zone-0     |
| 56c37f32-19a8-4f4b-9c3a-6a70d2e8fa49 | pvc-72ede75a-1c65-416b-9065-d3139c63d9d2 |    2 | CEPHFS      | available | False     | cephfstype      | rvasek-devstack@cephfsnative1#cephfs | manila-zone-0     |
+--------------------------------------+------------------------------------------+------+-------------+-----------+-----------+-----------------+--------------------------------------+-------------------+
```

Mounting a PVC into a Pod:
```
$  kubectl create -f pod.yaml 
pod/new-cephfs-share-snap-restore-pod created
$ kubectl get pod/new-cephfs-share-snap-restore-pod 
NAME                                READY   STATUS    RESTARTS   AGE
new-cephfs-share-snap-restore-pod   1/1     Running   0          9s
```

Clean-up was successful too.

**Comment by jichenjc** [comment]
@ramineni looks like pull-cloud-provider-openstack-check  need to be handled ? it should not be affected by env

**Comment by ramineni** [comment]
> @ramineni looks like pull-cloud-provider-openstack-check need to be handled ? it should not be affected by env

yes, Ill have a look at it. Thanks

**Comment by lingxiankong** [comment]
Conformance test passed (in a v1.22.0 cluster), result:

```
Ran 340 of 6432 Specs in 6340.585 seconds
SUCCESS! -- 340 Passed | 0 Failed | 0 Pending | 6092 Skipped
PASS
```

openstack-cloud-controller-manager functional test also passed by running `tests/e2e/cloudprovider/test-lb-service.sh`

**Comment by jichenjc** [comment]
/approve

looks good @lingxiankong I assume you will manual merge this anyway..

**Comment by lingxiankong** [comment]
Yeah, I will force merge it after receiving @ramineni's confirmation about cinder-csi test.

**Comment by ramineni** [comment]
> Yeah, I will force merge it after receiving @ramineni's confirmation about cinder-csi test.

@lingxiankong Thanks. I did run acceptance tests of cinder csi, https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-csi-cinder .  It is successful.

Should be good to go.

**Comment by lingxiankong** [comment]
> @lingxiankong Thanks. I did run acceptance tests of cinder csi, https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-csi-cinder . It is successful.
> 
> Should be good to go.

Great, here we go!

**Pull request merged**
