### PR TITLE
[occm] remove unused code

### PR DESCRIPTION
**Pull request by databus23**
As ensureLoadBalancer deferes to ensureOctaviaLoadBalancer for the octavia use case right away we can remove all references to octavia specific code in ensureLoadBalancer. This code is not used anymore.

Signed-off-by: Fabian Ruff <fabian.ruff@sap.com>

**What this PR does / why we need it**:
Remove unused code

**Special notes for reviewers**:

```release-note
NONE
```

### CODE REVIEW

**Comment by databus23** [comment]
I don't understand why the tests are failing. I'm not sure this is actually related to my changes or not. Most of the detail links point to something that seems unrelated to my code. If someone could point me to a usable error message it would be much appreciated.

**Comment by jichenjc** [comment]
/lgtm

sounds good to me

**Comment by databus23** [comment]
@jichenjc can we re-run the tests? What else is needed to move this forward?

**Comment by jichenjc** [comment]
@ramineni @lingxiankong can you help review this ? 

I don't think we need additional test... (overwrite the failed should be fine)

**Comment by lingxiankong** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.19
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.20

**Pull request merged**
