### PR TITLE
Add release procedure

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
This PR, adds release procedure for cloud provider openstack repo.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by adisky** [comment]
The content is mainly authored by @dims 
https://gist.github.com/dims/cefbdcfbacf867c315c119d7a2491c05

**Comment by adisky** [comment]
cc @dims @hogepodge @lingxiankong @jichenjc @ramineni reviews and suggestions are welcome :)

**Comment by dims** [comment]
/approve
/lgtm

Let's merge and iterate :)

**Comment by jichenjc** [comment]
given the discussion here:
https://etherpad.openstack.org/p/k8s-sig-ptg-train
https://etherpad.openstack.org/p/k8s-sig-ptg-train-repository-refactor

this release thing might be a little bit different?

**Pull request merged**
