### PR TITLE
Normalize function return, if block ends with a return statement, so …

### PR DESCRIPTION
**Pull request by sivanzcw**
* Fix golint error, if block ends with a return statement, so drop this else and outdent its block

### CODE REVIEW

**Comment by lingxiankong** [comment]
@sivanzcw Hi, thanks for the contribution, I didn't find the golint warning information from the issue description, it'd be great if you could provide some more information so that we could see the improvements with this PR.

**Comment by sivanzcw** [comment]
@lingxiankong  the golint warning related to this commit is as follow

```
root@kubernetes:~/workspace/code/src/k8s.io/cloud-provider-openstack# for line in `find ./ -type f | grep .go `;do echo $line; golint $line; done | grep 'if block ends with a return statement, so drop this else and outdent its block'
./pkg/identity/keystone/authorizer.go:62:10: if block ends with a return statement, so drop this else and outdent its block
./pkg/identity/keystone/authorizer.go:71:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
./pkg/identity/keystone/authorizer.go:86:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
./pkg/identity/keystone/authorizer.go:96:11: if block ends with a return statement, so drop this else and outdent its block
./pkg/util/mount/mount_linux.go:497:10: if block ends with a return statement, so drop this else and outdent its block
./pkg/util/mount/mount_linux.go:502:11: if block ends with a return statement, so drop this else and outdent its block
./pkg/csi/manila/driver.go:135:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
./pkg/flexvolume/flexvolume.go:267:10: if block ends with a return statement, so drop this else and outdent its block
```

**Comment by lingxiankong** [comment]
thanks!

/lgtm

**Comment by ramineni** [comment]
Thanks.
/approve

**Pull request merged**
