### PR TITLE
Add more testing scenarios jobs against K8S+OpenStack

### PR DESCRIPTION
**Pull request by liu-sheng**
**What this PR does / why we need it**:
- Add jobs trigger for triggering all the jobs by commenting "/retest" or "/test all" under a PR
- Add jobs trigger for triggering unit tests job by commenting "/test cloud-provider-openstack-unit" under a PR
- Add jobs trigger for triggering K8S+LBaaS(Octavia) scenario testing by commenting "/test cloud-provider-openstack-lb" under a PR
- Add jobs trigger for triggering K8S+keystone authentication/authorization scenario testing by comment "/test cloud-provider-openstack-auth" under a PR

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by liu-sheng** [comment]
check

**Comment by dims** [comment]
@liu-sheng @kiwik @animationzl should these jobs be failing?

**Comment by kiwik** [comment]
Hi @dims: local-up-cluster.sh updated, that casue cloud-provider-openstack-acceptance-test-keystone-authentication-authorization job failed, we have to update zuul job ansible script, By the other side, we plan to add external binary setup support in local-up-cluster.sh, like: k8s-keystone-auth, cinder-provisioner, cinder-csi-plugin, cinder-flex-volume-driver, that will make zuul integration easy for us.

**Comment by kiwik** [comment]
And cloud-provider-openstack-acceptance-test-lb-octavia jobs failing is wired, seems the floating IP is allocated successfully, but the whole process is timeout (timeout is 5 minutes), that only take 20~30 seconds in our test environment, we will try to find out the reason.

**Comment by dims** [comment]
seeing some flakiness... @kiwik @liu-sheng @animationzl do you recommend merging this right away?

**Comment by kiwik** [comment]
@dims , we are trying to find the root reason about the failing, if everything is ready, will ping you.

**Comment by kiwik** [comment]
Hi @dims , we found some bugs that is related with unit test code, that cause test failed in some times, https://github.com/kubernetes/cloud-provider-openstack/issues/80 , we are checking more failed tests log, and will append all of them in the comments. OpenLab already start to play its role yet :-)

**Comment by animationzl** [comment]
@dims there is a bug about TestVolumes unit test, please refer to this #81

**Comment by dims** [comment]
Merging this so i can test the changes to the test suite in https://github.com/kubernetes/cloud-provider-openstack/pull/82

/lgtm

**Pull request merged**
