### PR TITLE
Typo fix: fix some word error

### PR DESCRIPTION
**Pull request by angao**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by angao** [comment]
@NickrenREN review and add tag for these commits

**Comment by dixudx** [comment]
@angao Please squash your commits. No need to have multiple commits for simple typos.

**Comment by dixudx** [comment]
@dims Seems we need to enable #154 ASAP when it's ready. Several PRs are addressing typos.

**Comment by dims** [comment]
@dixudx we need to address this comment in 154 - https://github.com/theopenlab/openlab-zuul-jobs/pull/200#discussion_r185769602

**Pull request merged**
