### PR TITLE
[trivial] Remove travis.yml

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
File not needed

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
we are using openlab so this file is not used
/lgtm

**Comment by adisky** [comment]
cc @lingxiankong @dims for approval!!

**Pull request merged**
