### PR TITLE
Cherry-pick #1632 into release-1.21

### PR DESCRIPTION
**Pull request by MPV**
**What this PR does / why we need it**:
Cherry-pick #1632 into `release-1.21` branch.

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MPV** [comment]
@jichenjc Could you take a look? 

This attempts to fix issues in the `release-1.21` branch, seen in open backport attempts #1784 and #1775.

**Comment by ramineni** [comment]
@MPV Its not required or recommended to backport. 

/hold

**Comment by ramineni** [comment]
/close

Back port to previous branches not recommended, only bug fixes allowed

**Comment by MPV** [comment]
Ah, looks like skipping tests for backports instead was the resolution for those issues. Thanks for your time on this. 👍

**Pull request closed without merging**
