### PR TITLE
Updated package references from git.openstack.org to k8s.io

### LINKED ISSUE #7: Replace git.openstack.org/openstack/openstack-cloud-controller-manager with k8s.io/cloud-provider-openstack
We need to find and replace all instances of the earlier namespace we used to use with the new one.

### PR DESCRIPTION
**Pull request by hogepodge**
**What this PR does / why we need it**:

This PR updates package references from git.openstack.org to k8s.io.

**Which issue this PR fixes** 

fixes #7 

**Special notes for your reviewer**:

related PR : kubernetes/k8s.io#108

**Release note**:

```release-note 
Updated package references to k8s.io/cloud-provider-openstack/*
```

### CODE REVIEW

**Comment by hogepodge** [comment]
/hold

Waiting on kubernetes/k8s.io#108

**Comment by dims** [comment]
@hogepodge there's a hidden reference in Makefile too ... search for GIT_HOST and DEST at the top of the file

**Comment by hogepodge** [comment]
@dims updated

**Comment by dims** [comment]
looks like we have conflicts. please rebase

**Comment by dims** [comment]
kubernetes/k8s.io#108 has merged

/hold cancel

**Pull request merged**
