### PR TITLE
fix golint failures

### PR DESCRIPTION
**Pull request by FayerZhang**
**What this PR does / why we need it**:
/cleanup

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #28

**Special notes for your reviewer**:

**Release note**:
```NONE```

### CODE REVIEW

**Comment by kayrus** [comment]
Do these checks run automatically in tests?

**Comment by ramineni** [comment]
@FayerZhang Thanks for the PR. Looks good. 
Could you also make this script up-to-date https://github.com/kubernetes/cloud-provider-openstack/blob/master/hack/verify-golint.sh , doesn't seem to work as expected. not sure if it is my env issue.

**Comment by FayerZhang** [comment]
> @FayerZhang Thanks for the PR. Looks good.
> Could you also make this script up-to-date https://github.com/kubernetes/cloud-provider-openstack/blob/master/hack/verify-golint.sh , doesn't seem to work as expected. not sure if it is my env issue.
 please retry the script, and check my code again.  thanks!

**Comment by ramineni** [comment]
@FayerZhang I have ran the script both on master branch and your branch (checkedout locally) , Im getting the o/p Congratulations!  All Go source files have been linted. But ideally on master branch it should throw lint errors. So thought script needs to be fixed. Let me know if you have different results when run on master.

But this is different issue , can be corrected in separate PR if required.

**Pull request merged**
