### PR TITLE
Bump versions for 1.30

### PR DESCRIPTION
**Pull request by dulek**
**What this PR does / why we need it**:
Bumping versions for K8s 1.30.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by zetaab — APPROVED** [review]
/approve

**Comment by dulek** [comment]
/hold

This needs #2581 first. Also k3s 1.30 is not yet released, so I'm sure this'll fail CI.

**Review by zetaab — COMMENTED** [review]
hmm actually worth of updating those helm chart maintainers first

**Comment by zetaab** [comment]
@dulek can you rebase this as https://github.com/kubernetes/cloud-provider-openstack/pull/2581 is merged already

**Comment by zetaab** [comment]
I will close this and rebase it in #2589

**Pull request closed without merging**
