### PR TITLE
update link in mysql cinder pd example

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/cloud-provider-openstack/issues/893

### CODE REVIEW

**Comment by lingxiankong** [comment]
Please fix the PR description.

**Comment by ramineni** [comment]
This looks duplicate of https://github.com/kubernetes/cloud-provider-openstack/pull/892 , can we close this?

**Comment by ramineni** [comment]
> This looks duplicate of #892 , can we close this?

/close

**Pull request closed without merging**
