### PR TITLE
[manila-provisioner] Add get, create and update permissions for endpoints

### PR DESCRIPTION
**Pull request by brtknr**
(cherry picked from commit 08e36e465d59f89cdcdf9012a92012093b6e41af)
Signed-off-by: Bharat Kunwar <brtknr@bath.edu>

**The binaries affected**:

IMPORTANT: Please also add the binary name in the title, e.g.
`[openstack-cloud-controller-manager]: Add UDP protocol support`
unless the PR affects multiple binaries.

- [ ] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [x ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What this PR does / why we need it**:
Manila provisioner service account requires these permissions in 1.16.x to work. 

**Which issue this PR fixes**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adisky** [comment]
/lgtm
cc @gman0 @tombarron

**Comment by tombarron** [comment]
Nit: commit  header leaves out the verb 'delete', which is also added.

/lgtm
/approve

**Pull request merged**
