### PR TITLE
[k8s-keystone-auth] improve keystone connection trace.

### LINKED ISSUE #1207: [k8s-keystone-auth] Implement a tracing http roundtripper client
Affected binary:  k8s-keystone-auth

/kind feature

**What happened**:

Due to the following bug https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1892067, we
identified that the current log tracing levels aren't enough to diagnose  issues in the communication
to the keystone endpoints.

In particular,  this line https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/identity/keystone/keystone.go#L281 doesn't logs any error during the authorization
phase.

Also, would be very helpful to have http connection level tracing in order to see when a connection
is started, finished and or any timeouts ocurred, increasing the logging levels that can be useful when diagnosing issues in the communication to the keystone endpoints at the http level.

**What you expected to happen**:

* We would like to be able to see why an authentication failed in the kslog , why a token authorization failed,
and be able to enable trace level debugging for the http client.

### PR DESCRIPTION
**Pull request by niedbalski**
[k8s-keystone-auth] improve keystone connection trace.

* Log all errors on failures. (authorizeToken)
* Add httptrace transport if log level == 4.

Fixes #1207

**What this PR does / why we need it**:

Due to the following bug https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1892067, we
identified that the current log tracing levels aren't enough to diagnose issues in the communication
to the keystone endpoints.

In particular, this line https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/identity/keystone/keystone.go#L281 doesn't logs any error during the authorization
phase.

Also, would be very helpful to have http connection level tracing in order to see when a connection
is started, finished and or any timeouts ocurred, increasing the logging levels that can be useful when diagnosing issues in the communication to the keystone endpoints at the http level.

**Which issue this PR fixes(if applicable)**:
fixes #1207

### CODE REVIEW

**Comment by kayrus** [comment]
@niedbalski I don't think this is a proper concept. See #993 and #867. From my perspective it would be better to detach the client related logic to a separate package, add a trace logic there and reuse it for all cloud provider components. If we start introducing the logic for each component independently again, we will have a lot of duplicate code with a mess we had before.

**Comment by niedbalski** [comment]
@jichenjc I don't think the test failure is related to my change, any chance you can help me to check?

**Comment by jichenjc** [comment]
/retest
let's retest and see what happen @niedbalski 
and you might want to check with @kayrus on his comments above

**Comment by niedbalski** [comment]
Hello @kayrus 

Thank you for reviewing. I wonder if you could guide me on your idea of switching the scope of the createKeystoneClient method into something that's re-usable across components. 

This PR just intends to make the transport more verbose in situations on which communication is broken or
a failure event occurs in the authorization phase.

Thanks

**Comment by kayrus** [comment]
@niedbalski sorry for a late response. have you tried to use `--v=6` ? It should trace all HTTP calls. This feature was introduced in #867
If you want to introduce something new, then I just suggest to move out the client logic into a separate package: #993 
Unfortunately I don't have any specific requirements, since it should be quite straight-forward.

**Pull request closed without merging**
