### PR TITLE
Deduplicate OpenStack auth functions

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

It unifies all the OpenStack auth options and deduplicates code.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

#640

**Special notes for your reviewer**:

This PR is based on #733. I'll rebase this PR once #733 is merged.

**Release note**:

```release-note
Unify openstack authenticate options
```

### CODE REVIEW

**Comment by hogepodge** [comment]
@kayrus this looks great.

A couple of questions, if this is ready do you feel ok squashing the commit? I'm not sure we need the complete history and the changeset is fairly intuitive.

On the docs update, did the configuration api change? We would definitely want to alert the userbase to the change for the 1.16 release if that's the case.

Want to get some more eyes on it before approving, but /lgtm

/assign @adisky

**Comment by kayrus** [comment]
@hogepodge 

> if this is ready do you feel ok squashing the commit

commits can be squashed automatically in github web UI.

> On the docs update, did the configuration api change?

I kept the full backward compatibility, but additionally added new auth options to components. Unfortunately new options are not documented. I assume this must be a new PR with the docs refactoring.

**Comment by adisky** [comment]
@kayrus could you open a doc PR in parallel, it will be easier for reviewers

**Comment by kayrus** [comment]
@adisky updated the docs, where OS auth options were mentioned.

**Comment by kayrus** [comment]
I'm ok if you just merge this PR and close #733

**Comment by kayrus** [comment]
@adisky any concerns or comments on this PR?

**Comment by adisky** [comment]
@kayrus give me sometime to review, very busy this week, would to review it tomarrow

**Comment by kayrus** [comment]
@adisky do you have any updates on this PR? Concerns, objections?

**Comment by jborg** [comment]
Is this PR "only" blocked by flaky tests or does it need more work?

**Comment by adisky** [comment]
@jborg we need to be sure for this PR to pass the conformance tests, tests were flaky due to some other reasons, Tests are passing now, you need to rebase the PR to latest master, please rebase  after https://github.com/kubernetes/cloud-provider-openstack/pull/753 this one gets merged.

**Comment by adisky** [comment]
/lgtm
@lingxiankong @gman0 @tsmetana @tombarron PTAL
/priority-important-soon

**Comment by kayrus** [comment]
I was asked to squash this PR. If someone wants to see the detailed history, he can take a look on the https://github.com/kayrus/cloud-provider-openstack/tree/step-by-step. It has identical code, but not squashed.

**Comment by lingxiankong** [comment]
openstack-cloud-controller-manager test ok

**Comment by lingxiankong** [comment]
octavia-ingress-controller ok

**Pull request merged**
