### PR TITLE
Bump k8s deps to 1.25

### PR DESCRIPTION
**Pull request by olemarkus**
* openstack-cloud-controller-manager (occm)
* cinder-csi-plugin
* manila-csi-plugin
* k8s-keystone-auth
* client-keystone-auth
* octavia-ingress-controller
* magnum-auto-healer
* barbican-kms-plugin

**What this PR does / why we need it**:

Bumps all the k8s dependencies to 1.25. Also pulls in a couple of other deps upgrades.

**Release note**:

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by zetaab** [comment]
@jichenjc ideas what is going with manila e2e?

**Comment by olemarkus** [comment]
It looks like an old go version is used for that test.

**Comment by jichenjc** [comment]
>>>It looks like an old go version is used for that test.

I can overwrite this , I have no idea on the e2e test itself, @gman0 you happen to know?

**Comment by gman0** [comment]
Taking a look, thanks!

**Comment by gman0** [comment]
@jichenjc yes it is likely outdated golang compiler. Strange that cinder-csi didn't run into this.

Here we're installing the golang toolchain for manila e2e job:

https://github.com/kubernetes/cloud-provider-openstack/blob/40244ebe4897c4e5293a595ddf925f4962a4a5e8/tests/playbooks/test-csi-manila-e2e.yaml#L12-L13

But it is quite old:

https://github.com/kubernetes/cloud-provider-openstack/blob/40244ebe4897c4e5293a595ddf925f4962a4a5e8/tests/playbooks/roles/install-golang/defaults/main.yml#L1-L5

**Comment by gman0** [comment]
Let's see if https://github.com/kubernetes/cloud-provider-openstack/pull/1981 helps.

**Comment by gman0** [comment]
Second attempt in https://github.com/kubernetes/cloud-provider-openstack/pull/1983

**Comment by gman0** [comment]
@olemarkus https://github.com/kubernetes/cloud-provider-openstack/pull/1983 is now merged. Can you please rebase to see if the newer golang compiler helps?

**Comment by olemarkus** [comment]
```
No dice

https://https://go.dev/dl/go1.19.linux-amd64.tar.gz"
}

MSG:

Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>
````

Probably not temporary that one

**Comment by gman0** [comment]
Weird, https://github.com/olemarkus/cloud-provider-openstack/blob/k8s-125/tests/playbooks/roles/install-golang/defaults/main.yml already points to the correct location.

**Comment by olemarkus** [comment]
Moving on:
```
non-zero return code
...ignoring

TASK [install-csi-manila : fail] ***********************************************
fatal: [34.150.188.9]: FAILED! => {
    "changed": false
}

``

**Comment by gman0** [comment]
@olemarkus

```
TASK [install-csi-manila : Run functional tests for manila-csi-plugin] *********
fatal: [34.150.188.9]: FAILED! => {
    "changed": true,
    "cmd": "set -x\nset -e\nset -o pipefail\n\nset +x; source /home/stack/devstack/openrc demo demo > /dev/null; set -x\n\ncd /root/src/k8s.io/cloud-provider-openstack\n\n# GATEWAY_IP is the default value in devstack\nmkdir -p /var/log/csi-pod\nGATEWAY_IP=172.24.5.1 \\\nOS_RC=/home/stack/devstack/openrc \\\ngo test -v ./cmd/tests/manila-csi-e2e-suite/manila_csi_e2e_suite_test.go \\\n  -ginkgo.v \\\n  -ginkgo.progress \\\n  -ginkgo.skip=\"\\[Disruptive\\]|\\[sig-storage\\]\\s+\\[manila-csi-e2e\\]\\s+CSI\\s+Volumes\\s+\\[Driver:\\s+nfs.manila.csi.openstack.org\\]\\s+\\[Testpattern:\\s+Dynamic\\s+PV\\s+\\(default\\s+fs\\)\\]\\s+provisioning\\s+should\\s+provision\\s+storage\\s+with\\s+any\\s+volume\\s+data\\s+source\\s+\\[Serial\\]\" \\\n  -ginkgo.focus=\"\\[manila-csi-e2e\\]\" \\\n  -ginkgo.noColor \\\n  -report-dir /var/log/csi-pod \\\n  -timeout=0 | tee \"/var/log/csi-pod/manila-csi-e2e.log\"\n",
    "delta": "0:00:56.855692",
    "end": "2022-09-01 17:52:22.257551",
    "rc": 1,
    "start": "2022-09-01 17:51:25.401859"
}

STDOUT:

/tmp/go-build433980122/b001/main.test flag redefined: ginkgo.seed
panic: /tmp/go-build433980122/b001/main.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000114180, {0x2125498, 0x301b420}, {0xc000504090, 0xb}, {0x1ddf5f2, 0x2a})
	/usr/local/go/src/flag/flag.go:980 +0x2f9
flag.(*FlagSet).Int64Var(...)
	/usr/local/go/src/flag/flag.go:767
github.com/onsi/ginkgo/v2/types.bindFlagSet({{0xc000543500, 0x20, 0x21}, {0x1ae0aa0, 0xc0003fc240}, {0x2fe98c0, 0xd, 0xd}, {{0x0, 0x0}, ...}, ...}, ...)
	/root/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:161 +0x709
github.com/onsi/ginkgo/v2/types.NewAttachedGinkgoFlagSet(...)
	/root/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:113
github.com/onsi/ginkgo/v2/types.BuildTestSuiteFlagSet(0x301b420, 0x301a820)
	/root/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/config.go:346 +0x5d8
github.com/onsi/ginkgo/v2.init.0()
	/root/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/core_dsl.go:47 +0x66
FAIL	command-line-arguments	0.030s
FAIL
```

**Comment by gman0** [comment]
go.mod contains v1 and v2 ginkgo modules (possibly causing these flag redefinition panics). manila-csi e2e test uses ginkgo v1, I'm trying to move it to v2.

**Comment by olemarkus** [comment]
Ah. yeah k/k moved to ginkgo v2 so that has become more or less mandatory. But from my experience, migration has been straightforward.

**Comment by gman0** [comment]
@olemarkus I can't seem to be able to push into your PR branch. After checking the patch, could you please `git apply` https://gist.github.com/gman0/92df8f4b6518f8ff81cc5786be3c459e into this PR?

I'm not sure we can do this ginkgo v2 move easily without fiddling with deps too much and duplicating work with this PR.

**Comment by olemarkus** [comment]
I had to go a bit further than your patch, @gman0. The whole csi test framework and utils needed to be bumped to remove the v1 dependencies.

**Comment by olemarkus** [comment]
The manilla sanity checks fails now due to lacking/unexpected capabilities being advertised. I have no idea what is appropriate to add here.

**Comment by gman0** [comment]
@olemarkus I'm fixing those now, thanks for the other patch!

**Comment by gman0** [comment]
https://github.com/kubernetes/cloud-provider-openstack/pull/1987 should fix manila-csi's sanity test.

**Comment by gman0** [comment]
@olemarkus https://github.com/kubernetes/cloud-provider-openstack/pull/1987 was merged. Can you rebase please?

**Comment by olemarkus** [comment]
Done

**Comment by gman0** [comment]
@jichenjc @zetaab CI is now passing. Can you PTAL?

**Pull request merged**
