### PR TITLE
[cinder-csi-plugin] Cleanup: handle errors from GetDevicePath

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:
Now GetDevicePath from metadata doesn't return an error if something bad happens. This makes it difficult to debug Cinder CSI driver.

This commit modifies the function to return an error value, and also adds additional logging that should help with debugging.

```release-note
NONE
```

### CODE REVIEW

**Review by ricolin — COMMENTED** [review]
/lgtm

**Comment by jichenjc** [comment]
/approve

thanks for the PR

**Pull request merged**
