### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by mikejoh**
**What this PR does / why we need it**:
Fixes minor typos.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mikejoh** [comment]
Hi, for me that are kind of new to the whole contribution process,  could someone explain why the builds fail constantly on this PR? Is there something that i can/should do? I tried to find the exact reason looking in logs and zuul but i could not find my way to what’s causing the failed builds.

**Comment by jichenjc** [comment]
it's likely to be the openlab CI has some issue, I think you can ask here:
https://kubernetes.slack.com/messages/C0LSA3T7C/ 
I already asked just now :) and hopefully get some response @mikejoh

**Pull request merged**
