### PR TITLE
Cascading delete loadbalancer resources for Octavia

### LINKED ISSUE #264: Loadbalancer: Use cascading delete when using Octavia
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The current `EnsureLoadBalancerDeleted` method involves too many API calls to the load balancing service.

**What you expected to happen**:
Octavia already supports [cascading deletion](https://developer.openstack.org/api-ref/load-balancer/v2/index.html#remove-a-load-balancer) for the load balancer.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
gophercloud also supports the feature.

**Environment**:
- openstack-cloud-controller-manager version: master

### PR DESCRIPTION
**Pull request by lingxiankong**
**What this PR does / why we need it**:
Cascading delete loadbalancer resources for Octavia when deleting LoadBalancer type service.

**Which issue this PR fixes**: 
fixes #264

**Special notes for your reviewer**:
Reasons to use cascading delete:

- Reduce API calls to Octavia from 10+ to only 1. More API calls means
  more exception risk.
- Simplify the code logic

Tested on my k8s environment on top of OpenStack.

**Release note**:
NONE

### CODE REVIEW

**Comment by lingxiankong** [comment]
@dims could you please have a review for this one?

**Comment by lingxiankong** [comment]
Not sure there are other people active for this repo.

**Comment by FengyunPan2** [comment]
Sorry to delay.
/lgtm

**Pull request merged**
