### PR TITLE
Update manifests to v1.15 images

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
pinned images to v1.15 for release branch v1.15 to avoid version compatibility issues
https://github.com/kubernetes/cloud-provider-openstack/issues/431

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```
`NONE.`

### CODE REVIEW

**Comment by adisky** [comment]
> /test cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12

@jichenjc it will fail, need to override

**Comment by jichenjc** [comment]
sounds good , leave to other folks to take a look~

**Comment by hogepodge** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12 
/approve

**Pull request merged**
