### PR TITLE
[cinder-csi-plugin]Add UT for create volumes with volume type and az

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
@ramineni please help check this , thanks

**Comment by ramineni** [comment]
/override openlab/cloud-provider-openstack-multinode-csi-migration-test

**Pull request merged**
