### PR TITLE
remove ExternalID function

### PR DESCRIPTION
**Pull request by jichenjc**
https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L139
don't have this anymore

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by adisky** [comment]
@jichenjc please fix the format,  otherwise lgtm

**Comment by jichenjc** [comment]
my local succeed, I don't know why fail upstream...

**Pull request merged**
