### PR TITLE
Add Test to generate listener options [OCP]

### PR DESCRIPTION
**Pull request by FavourEva**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dulek** [comment]
Nice! It's missing a case when `Protocol` ends up as `listeners.ProtocolHTTP`, but I think this is good enough.
/lgtm
/approve

**Comment by FavourEva** [comment]
> Nice! It's missing a case when `Protocol` ends up as `listeners.ProtocolHTTP`, but I think this is good enough. /lgtm /approve

You're right! I would have to open a new PR including that case to the test

**Pull request merged**
