### PR TITLE
[cinder-csi-plugin] Bump chart to 2.1.1

### PR DESCRIPTION
**Pull request by MPV**
**What this PR does / why we need it**:
Makes these changes available in a version:
- https://github.com/kubernetes/cloud-provider-openstack/pull/1789
- https://github.com/kubernetes/cloud-provider-openstack/pull/1792

**Which issue this PR fixes(if applicable)**:
See those PRs.

**Special notes for reviewers**:
Included changes since last version, https://github.com/kubernetes/cloud-provider-openstack/releases/tag/openstack-cinder-csi-2.1.0:
```shell
$ git log --oneline openstack-cinder-csi-2.1.0.. charts/cinder-csi-plugin
31236ba [cinder-csi-plugin] Configurable secret filename (#1789)
c55b41d [Cinder-csi-plugin] Provide capability to add extra labels for Cinder (#1792)
204a990 Updated CLOUD_CONFIG in helm chart. (#1747)
0d1d1ec [helm charts] Make the chart versions consistent with release-1.23 (#1745)
```

**Release note**:

```release-note
[cinder-csi-plugin] Make CLOUD_CONFIG secret keys consistent in helm chart for better re-usability 
[cinder-csi-plugin] Make CLOUD_CONFIG secret filename configurable in helm chart for backwards-compatibility
[cinder-csi-plugin] Adding optional extra labels to be set in `.Values.extraLabels` in Helm Chart.
```

### CODE REVIEW

**Comment by MPV** [comment]
@lingxiankong maybe has input (seeing as they've shared thoughts on release process before)?

**Comment by MPV** [comment]
Also not sure whether this should be bumped in the [release-1.23](https://github.com/kubernetes/cloud-provider-openstack/tree/release-1.23) branch or in master?

I'm thinking of the change you made over at https://github.com/kubernetes/cloud-provider-openstack/pull/1745/files @lingxiankong.

**Comment by MPV** [comment]
If we'd prefer to bump the patch version from `1.23` branch, I guess we should backport those changes, i.e. https://github.com/kubernetes/cloud-provider-openstack/pull/1785? Or if we go with this PR, we could close that backport I guess.

**Comment by ramineni** [comment]
@MPV In general the charts are released only with CPO release. 
This doesnt look into me as potential backport because its not a bug , but extra capability is being added.

/hold

**Comment by ramineni** [comment]
As charts would be released along with major release. Closing this

/close

**Pull request closed without merging**
