### PR TITLE
[1.28.1] 1.28.1 release

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

This PR bumps a release version for manifests and docs using a new `hack/bump-release.sh` script

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by zetaab — CHANGES_REQUESTED** [review]
you are missing one file https://github.com/kayrus/cloud-provider-openstack/blob/r128/examples/webhook/keystone-deployment.yaml#L21 otherwise looks good! If you can fix that

**Review by zetaab — APPROVED** [review]
/lgtm

**Comment by dulek** [comment]
/test openstack-cloud-controller-manager-e2e-test

Looks like k3s update breaks CI?

**Comment by kayrus** [comment]
@dulek yes, and I wonder why.

**Comment by dulek** [comment]
/test openstack-cloud-controller-manager-e2e-test-release-128

DevStack haven't deployed.

**Pull request merged**
