### PR TITLE
Update to k/k 1.15.0

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
This PR updates to latest kubernetes release 1.15.0

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
`NONE`

```release-note
```

### CODE REVIEW

**Comment by adisky** [comment]
/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12

**Comment by adisky** [comment]
/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.13

**Comment by adisky** [comment]
/override cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12

**Comment by hogepodge** [comment]
/override cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12
/lgtm

**Comment by hogepodge** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12

**Pull request merged**
