### PR TITLE
Adds ZUUL job for manila-provisioner

### PR DESCRIPTION
**Pull request by gman0**
**What this PR does / why we need it**:
Adds a ZUUL job for manila-provisioner acceptance test
also adds manila-provisioner binary to `.gitignore`

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

@gman0 can you please rebase?

**Comment by gman0** [comment]
@dims Will do but there are still issues with the zuul job itself, I'll have to fix those first

**Comment by dims** [comment]
@gman0 Do we want to resurrect this? (please ping me on #sig-openstack slack or #askopenlab on IRC).

**Comment by gman0** [comment]
@dims yes, sorry for taking such a ridiculously long time with this, i was just too busy with other things. It's almost ready, a cephfs share gets successfully created but when it's time to mount the volume into a Pod, it fails with the following error:

```
E0918 05:59:10.317905   14668 mount_linux.go:151] Mount failed: exit status 110
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/cf76d30c-bb07-11e8-ac28-fa163ebec176/volumes/kubernetes.io~cephfs/pvc-cf42fae2-bb07-11e8-ac28-fa163ebec176 --scope -- mount -t ceph -o name=pvc-cf42fae2-bb07-11e8-ac28-fa163ebec176,secret=AQDxk6Bb0MsSCRAAUEp6oGkFs5NfkACJLLdrvA== 192.168.0.22:6789:/volumes/_nogroup/ece5b589-28ad-4921-8273-3480d3bfe1c5 /var/lib/kubelet/pods/cf76d30c-bb07-11e8-ac28-fa163ebec176/volumes/kubernetes.io~cephfs/pvc-cf42fae2-bb07-11e8-ac28-fa163ebec176
Output: Running scope as unit run-rb9bc0e351db7423c8ed45ea387ece9ce.scope.
mount error 110 = Connection timed out
```

It's not very clear to me why is it timing out.

**Comment by dims** [comment]
@kiwik @liu-sheng can you please help figure this out?

**Pull request closed without merging**
