### PR TITLE
Add OWNERS for manila CSI driver

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
Ownership for Manila CSI driver

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE.
```

### CODE REVIEW

**Comment by gman0** [comment]
The file being added in this PR is for the Manila external provisioner (`pkg/share/manila/OWNERS`). I suggest adding OWNERS to `pkg/csi/manila` as well if everyone agrees.

**Comment by tombarron** [comment]
> The file being added in this PR is for the Manila external provisioner (`pkg/share/manila/OWNERS`). I suggest adding OWNERS to `pkg/csi/manila` as well if everyone agrees.

Yeah I was going to ask about this.  We Manila folks (Goutham and I) have been reviewing and testing Robert's CSI stuff and haven't worked with the original non-CSI Manila plugin.  I know that it's still in use currently (e.g. at CERN) but my impression is that users will over time switch to the CSI plugin.

**Comment by ramineni** [comment]
@gman0 @tombarron agree, we could add in CSI/manila as well

**Comment by ramineni** [comment]
@tombarron looks like your membership request is still pending , could you update the PR as per comments

**Comment by tombarron** [comment]
@ramineni Thanks, hopefully it's formatted correctly now.

**Comment by lingxiankong** [comment]
/lgtm

Thanks for taking the responsibility for the manila stuff!

**Pull request merged**
