### PR TITLE
Fix `make import-boss` gate failure 

### LINKED ISSUE #1588: gate failure: running `make import-boss`
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
```
[root@m5404019 cloud-provider-openstack]# make import-boss
echo "installing import-boss"
installing import-boss
go get -u k8s.io/code-generator/cmd/import-boss
go: downloading k8s.io/code-generator v0.21.0
go: found k8s.io/code-generator/cmd/import-boss in k8s.io/code-generator v0.21.2
go: downloading k8s.io/klog/v2 v2.9.0
go: downloading k8s.io/gengo v0.0.0-20210707163844-888f71863374
go: downloading github.com/go-logr/logr v1.0.0
go: downloading golang.org/x/tools v0.1.4
go: downloading golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c
go: downloading golang.org/x/mod v0.4.2
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: sigs.k8s.io/yaml upgrade => v1.2.0
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/sys upgrade => v0.0.0-20210630005230-0f9fa26af87c
go: k8s.io/klog/v2 upgrade => v2.9.0
go: github.com/spf13/pflag upgrade => v1.0.5
go: golang.org/x/tools upgrade => v0.1.4
go: golang.org/x/mod upgrade => v0.4.2
go: github.com/go-logr/logr upgrade => v1.0.0
go: k8s.io/gengo upgrade => v0.0.0-20210707163844-888f71863374
# k8s.io/klog/v2
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:705:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:724:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:742:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:763:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:782:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:783:3: undefined: logr.WithCallDepth
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:794:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:795:3: undefined: logr.WithCallDepth
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:915:9: invalid operation: log != nil (mismatched types logr.Logger and nil)
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:919:4: undefined: logr.WithCallDepth
.go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:919:4: too many errors
make: *** [Makefile:186: import-boss] Error 2

```

looks like someone has same issue
https://golangrepo.com/repo/go-logr-logr

not sure we need some changes or rely on other repo to act, tracking here

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
This PR enables installing import-boss using go install command

**Which issue this PR fixes(if applicable)**:
fixes #1588

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
seems test passed, looks like go get is clone and install
while install is directly install

so something in build stage? curoius why the error occurs

**Comment by adisky** [comment]
> seems test passed, looks like go get is clone and install
> while install is directly install
> 
> so something in build stage? curoius why the error occurs

possibly go get have different behaviours inside/outside a gomodule directory, go install only installs specific module without touching the go.mod file.

**Review by adisky — COMMENTED** [review]
/approve

**Comment by jichenjc** [comment]
didn't have time to dig into real issue, but continuous TIMEOUT seems an env issue again

**Comment by ramineni** [comment]
@jichenjc Looks like some issue as its consistent failure. I'll have a look if it fails again.

**Comment by ramineni** [comment]
@lingxiankong I guess we can override the e2e test for this PR to unblock in meantime.

**Comment by ramineni** [comment]
@jichenjc @lingxiankong Looks like we have again volume overlimit issue
2021-07-13 05:22:44.520746 | ubuntu-focal-citynetwork | {"overLimit": {"message": "VolumeLimitExceeded: Maximum number of volumes allowed (100) exceeded for quota 'volumes'.", "code": 413, "retryAfter": "0"}}

**Comment by jichenjc** [comment]
we thought the periodic task can fix the problem but seems gate failure more than 2 days ..
guess need admin's help again

**Comment by ramineni** [comment]
> we thought the periodic task can fix the problem but seems gate failure more than 2 days ..
> so the job must be triggered but not able to mitigate
> 
> guess need admin's help again

@jichenjc I dont see the job getting triggerred. http://status.openlabtesting.org/builds?project=kubernetes%2Fcloud-provider-openstack&pipeline=periodic-14%09 . Is there different place to check whether cleanup job has run or not?

**Comment by jichenjc** [comment]
I don't know , maybe @lingxiankong @chrigl knows? 

https://github.com/theopenlab/openlab-zuul-jobs/pull/1149/files shows that the jobs is suppsoed to run every day at 22:00  ..

**Comment by lingxiankong** [comment]
> @jichenjc I dont see the job getting triggerred. http://status.openlabtesting.org/builds?project=kubernetes%2Fcloud-provider-openstack&pipeline=periodic-14%09 . Is there different place to check whether cleanup job has run or not?

It's here http://status.openlabtesting.org/builds?pipeline=periodic-22#

From the error message, the job failed to delete volumes.

@jichenjc I think setting up devstack and k3s in the CI host could remove that dependency on citynetwork volumes.

**Comment by lingxiankong** [comment]
/override openlab/cloud-provider-openstack-e2e-test-csi-cinder

**Comment by jichenjc** [comment]
>>>@jichenjc I think setting up devstack and k3s in the CI host could remove that dependency on citynetwork volumes.

agree , made some progress but not that much, stuck at too many other things now , hopefully spend some time on this soon

**Pull request merged**
