### PR TITLE
[magnum-auto-healer] Fix autohealer restart issue

### LINKED ISSUE #1333: [magnum-auto-healer] Magnum auto healer restart many times
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Magnum auto healer restarts many times

**What you expected to happen**:

Magnum auto healer shouldn't restart so many times.

**How to reproduce it**:

If the Magnum API is slow for any reason, magnum-auto-healer may fail to get cluster information. And user will see the magnum-auto-healer restart.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 
- OpenStack version: 
- Others:

### PR DESCRIPTION
**Pull request by openstacker**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #1333 

**Special notes for reviewers**:

**Release note**:

```release-note
[magnum-auto-healer] Fix magnum-auto-healer restart issue
```

### CODE REVIEW

**Comment by jichenjc** [comment]
a pretty straightforward fix, fast approve

**Comment by openstacker** [comment]
@jichenjc Thank you, my friend.

**Comment by lingxiankong** [comment]
@openstacker Could you please provide more detail for the release note?

**Comment by lingxiankong** [comment]
Never mind, I have changed that.

**Pull request merged**
