### PR TITLE
Implement arguments fallback for client-keystone-auth

### PR DESCRIPTION
**Pull request by johscheuer**
**What this PR does / why we need it**:

Without this PR it's not possible to only use arguments in the `client-keystone-auth` and a pipe.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes: https://github.com/kubernetes/cloud-provider-openstack/issues/476
**Special notes for your reviewer**:

**Release note**:

```release-note
client-keystone-auth: change the default behavior to use cli arguments if set otherwise use env variables for authentication
```

### CODE REVIEW

**Comment by johscheuer** [comment]
A side effect of this approach is the line `Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]`:

```bash
kubectl get po --all-namespaces | grep 'example'
Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]
example         details-v1-68c7c8666d-gr9h2                           2/2     Running     0          8h
example         productpage-v1-54d799c966-f4lnt                       2/2     Running     0          8h
example         ratings-v1-8558d4458d-p87hs                           2/2     Running     4          14h
example         reviews-v1-cb8655c75-tmc25                            2/2     Running     0          8h
example         reviews-v2-7fc9bb6dcf-ng67k                           2/2     Running     0          8h
example         reviews-v3-c995979bc-zxcgj                            2/2     Running     0          8h
```

We could omit this error if the token fetch was successfully and otherwise print it.

**Comment by hogepodge** [comment]
This patch needs a release note and a documentation update since it's making a major change to the auth interface.

**Comment by johscheuer** [comment]
@hogepodge I added a release note actually nothing (at least from the user point of view) has changed here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-client-keystone-auth.md#input-and-output-formats expect that now "only arguments" are working.

**Pull request merged**
