### PR TITLE
[occm] Skip External network with IPv6 for FIPs creation

### PR DESCRIPTION
**Pull request by MaysaMacedo**
OpenStack does not support creation of floating IPs
with IPv6. However, it's still possible to exist external
networks with IPv6 Subnets, which could break the creation
of Floating IPs for a load-balancer if CCM uses it.
This commit avoids this issue by making sure only external
networks with IPv4 Subnets are used when creating a Floating IP.

**Which issue this PR fixes(if applicable):**
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1993

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
code works for me ,
can you help create an issue so that we can track the issue itself ? Thanks @MaysaMacedo

**Comment by MaysaMacedo** [comment]
> code works for me , can you help create an issue so that we can track the issue itself ? Thanks @MaysaMacedo

Sure, here it's https://github.com/kubernetes/cloud-provider-openstack/issues/1993.
Thanks!

**Comment by jichenjc** [comment]
/lgtm

thanks~

**Pull request merged**
