### PR TITLE
adding eudev to alpine image for udevadm

### PR DESCRIPTION
**Pull request by dricoco**
**What this PR does / why we need it**:
fixing issue #592 
**Which issue this PR fixes** : 
fixes # 592

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dricoco** [comment]
test looks broken
2019-05-16 16:52:56.936497 | ubuntu-xenial-vexxhost | error: error parsing kube-dns.yaml: error converting YAML to JSON: yaml: line 50: did not find expected ',' or '}'

**Comment by dricoco** [comment]
Will this PR be merged ?

**Comment by dricoco** [comment]
@dixudx could you merge this PR ?

**Comment by ramineni** [comment]
Thanks.
/lgtm

**Comment by dricoco** [comment]
Those test seems quite broken imho... :)

**Comment by dricoco** [comment]
ok we just need an approval label I guess now :)

**Pull request merged**
