### PR TITLE
occm: Fix LoadBalancer deletion when the underlying LoadBalancer does…

### PR DESCRIPTION
**Pull request by jichenjc**
… not exist (#1913)

cherry pick #1913

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@jichenjc , thanks for the cherry-pick!

**Comment by chrigl** [comment]
/override openstack-cloud-csi-cinder-e2e-test-release-123
/override openstack-cloud-csi-manila-e2e-test-release-123

Both components are not affected by those changes.

**Pull request merged**
