### PR TITLE
keystone-webhook-documentation: Use consistent names for ConfigMap

### PR DESCRIPTION
**Pull request by mgoerens**
* Fix some typos

**What this PR does / why we need it**:
Documentation update: I ran into some issues following the documentation, because the name of the ConfigMap used was inconsistent.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes the name of the ConfigMap so it's consistent across the whole document, and some small typos.

### CODE REVIEW

**Comment by mgoerens** [comment]
CLA signed

**Comment by ramineni** [comment]
@mgoerens It says commit missing Github User , could you ensure both match as stated here: https://github.com/kubernetes/community/blob/master/CLA.md#4-ensure-your-github-e-mail-address-matches-address-used-to-sign-cla

**Comment by mgoerens** [comment]
@ramineni This should be fixed now, thanks

**Comment by lingxiankong** [comment]
/lgtm

Thanks for the fix!

**Pull request merged**
