### PR TITLE
Update share OWNERS file

### PR DESCRIPTION
**Pull request by tombarron**
**What this PR does / why we need it**: Update the new manila share OWNERS file with the current active set.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by ramineni** [comment]
Only after added as members of the org, then only can be added here, thats the reason showing invalid-owners-file

**Comment by tombarron** [comment]
> Only after added as members of the org, then only can be added here, thats the reason showing invalid-owners-file

@gouthamr and @tsmetana are already members and @gman0 is joining so hopefully this issue will resolve itself soon.

**Comment by adisky** [comment]
Thanks!!
/approve

**Pull request merged**
