### PR TITLE
cherry pick support mounting btrfs volumes by the cinder-csi-plugin (#1941) to 1.24

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

cherry pick #1941
update go fmt with all files

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
@shaardie @gman0 @zetaab can any of you lgtm to this so we can merge backport fix?

**Comment by gman0** [comment]
@jichenjc can you override the manila e2e test?

**Comment by jichenjc** [comment]
I don't know whether it's env issue ?

**Comment by jichenjc** [comment]
@zetaab @gman0 please help lgtm here.. thanks

**Pull request merged**
