### PR TITLE
[cinder-csi-plugin] bump CSI sidecar versions to latest

### PR DESCRIPTION
**Pull request by jauru**
[cinder-csi-plugin] Bump CSI sidecar versions to latest. Update related RBAC.

**What this PR does / why we need it**:
Volume doesn't get deleted from OpenStack if related PV is deleted by a user.

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kayrus** [comment]
@jauru thank you for your PR. Can you also bump the corresponding sidecars for Manila CSI charts?

**Comment by zetaab** [comment]
as this says cinder, maybe better to update manila stuff in separate prs

/approve

**Comment by jauru** [comment]
Yes, I can bump Manila versions also with a separate PR, but I don't have a way to test it.

**Pull request merged**
