### PR TITLE
Cut 1.28.2

### LINKED ISSUE #2531: [barbican-kms-plugin] Container broken in v1.28.1
/kind bug

The `barbican-kms-plugin:v1.28.1` does not start as the inner command does not recognize the flags correctly. This is due to the fact that flags are parsed before they are declared in the `main.go` code. This behaviour has been solved by PR #2325  , but the fix has not been back-ported to v1.28.1.

### PR DESCRIPTION
**Pull request by dulek**
**What this PR does / why we need it**:
This is to include fixes to #2531 in a release.

**Which issue this PR fixes(if applicable)**:
fixes #2531

```release-note
NONE
```

### CODE REVIEW

**Comment by dulek** [comment]
/retest

Looks like we just suddenly lost a VM, shouldn't be caused by this patch.

**Comment by dulek** [comment]
@kayrus, @jichenjc, @zetaab: This is ready for a review.

**Review by kayrus — APPROVED** [review]
LGTM, thanks!
Do you plan to make 1.27 release as well?

**Pull request merged**
