### PR TITLE
Support Cinder API version configuration

### LINKED ISSUE #212: Support Cinder API version configuration in CSI plugin
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**: 

There are lots of OpenStack users who are using Cinder v1 and Cinder v2 API. 
But now the Cinder CSI Plugin is only supporting Cinder V3.  For the end users, it has no way to set other Cinder API version like v1 and v2.

**What you expected to happen**:

Cinder version should be supported in Cinder CSI Plugin.
It can be configured like [kubernetes in tree cloud provider](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/).

For example:
```
[BlockStorage]
bs-version=v2
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by edisonxiang**
**What this PR does / why we need it**:

Support Cinder API version configuration in Cinder CSI Plugin.
It can be configured in the cloud.conf.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #212

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by flaper87** [comment]
I'm actually a bit torn on this one. Do we want for old versions to be used? (especially v1)

What value would this bring (besides supporting environments with older versions) compared to the maintenance cost of those APIs?

I can see the value of this if there was a new Cinder API but I really hope there won't be :smile: 

@j-griffith thoughts?

**Comment by edisonxiang** [comment]
@flaper87 thanks your reply. The value I see is that some users are using cinder v2.  We could not give up the users who is using the old cinder API. Actually I also totally agree your view point:)
> I can see the value of this if there was a new Cinder API

**Comment by flaper87** [comment]
@edisonxiang mmh, could we then limit this to cinder version >=2? I'm still a bit unsure on whether it's worth adding this code now or just wait until everything else matures a bit before we do it. We don't really have many users of this plugin yet (AFAIK, at least).

**Comment by j-griffith** [comment]
I really don't want to mix in support for V1 or V2 API's here.  The thing is; V1 has been out of support for "years" now.  I'd strongly object to adding the support burden of that.

As far as V2, it's sort of pointless in terms of functionality (V3 is a superset), but it is possible the deployment is still stuck back on Pre Newton I guess?  IMO thought that's still a >2 year old deployment and I'm not sure about supporting it with CSI.  We have enough challenges getting V3 and microversions all sorted IMO.

:-1:

**Comment by flaper87** [comment]
@j-griffith yeah, exactly the feedback I was looking for and I fully agree with you.

@edisonxiang Do you agree with our comments here?

**Comment by embik** [comment]
Hey @dims @j-griffith @edisonxiang, we don't have cinder v3 running yet and I would like to see this being discussed further. The CSI plugin is basically my last hope for dynamic provisioning and I don't have any influence on cinder v3 being activated.

**Comment by j-griffith** [comment]
@edisonxiang 
> We may not support cinder v1. But cinder v2 support is very necessary for the end users.
So I can remove codes about cinder v1 and remain cinder v2.
Do you agree?

Seems like a reasonable compromise, the one detail I was trying to point out though is that in fact **_V3.0 is V2_**; so rather than mess with that nuance just implement V3, we can "make it work" with a V2 deployment.  Looking forward that means that we *only* have to deal with micro versions going forward.  

@embik points out
> we don't have cinder v3 running yet and I would like to see this being discussed further. The CSI plugin is basically my last hope for dynamic provisioning and I don't have any influence on cinder v3 being activated.

I think we could solve that internally but that might be "too much magic" so I'm good with just dropping V1 and implementing V2 and V3

**Comment by dims** [comment]
So, @edisonxiang what do we want to do here?

**Comment by dims** [comment]
/close

please reopen when needed (or ping me and i'll take care of it)

**Comment by xlucas** [comment]
Is this PR still being considered? If so, can I help ?

**Comment by adisky** [comment]
@dims @flaper87 @edisonxiang @j-griffith ^

**Comment by nabheet** [comment]
Is there any way we could get this re-opened and merged? I am not sure my employer will ever upgrade to v3. It would be wonderfully great to have this support Cinder V2. I would help but it might a bit beyond my skills at this point.

**Comment by adisky** [comment]
@dims @flaper87 @j-griffith ^ It seems many people wants v2 support!!

**Comment by dims** [comment]
cc @hogepodge

**Comment by hogepodge** [comment]
Reopening for discussion.

**Comment by jianglingxia** [comment]
i hope commity can supprot v2,many people now use the v2 version and maybe in short time to upgrade  to v3,thanks

**Comment by nabheet** [comment]
Sorry to repeatedly harass you guys - can someone pretty please with sugar on top merge this PR? Or help fix the tests? I am not sure how much time @edisonxiang has to devote to this. But y’all would be a life saver if V2 support gets included in CSI Cinder. I woul offer a bribe but I am not sure how ethical it would be. 😀

**Comment by nabheet** [comment]
Yeah I saw that ... I was making a general request for someone to help fix the issues, without using those words directly. 😀

I was politely pleading primarily because it will take me a while to upgrade my skills sets to fix the tests.

**Comment by nabheet** [comment]
Or if it’s just merge conflicts maybe I could fork and do it in a separate PR ... I should be able to look at it next week.

**Comment by adisky** [comment]
@nabheet give me sometime, I will try to fix it

**Comment by jianglingxia** [comment]
excuse me! i see the code there has computev2 package to call , the issue mean that csi plugin only support v3 blockstorage but support nova v2 version? is that right?thanks all!

**Comment by nabheet** [comment]
@adisky were you able to spend any time on this issue?

**Comment by adisky** [comment]
@nabheet  sorry I couldn't get time to work on this, if you still want this, Open an issue in this repo, and tag it as help wanted!!

**Comment by adisky** [comment]
as https://github.com/kubernetes/cloud-provider-openstack/issues/212, this issue is stale now, and it is for V1 and V2, after discussions here, we agreed to support V2, so it is better to open a new issue

**Comment by adisky** [comment]
/close 
no update from long time

**Pull request closed without merging**
