### PR TITLE
Add strigazi to reviewers

### PR DESCRIPTION
**Pull request by strigazi**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by hogepodge** [comment]
Merged in #39.
Please close.

**Comment by strigazi** [comment]
Thanks

**Pull request closed without merging**
