### PR TITLE
Enforce running Makefile from $DEST

### PR DESCRIPTION
**Pull request by dims**
We have had several problems:
- folks checking out to a random directory outside their GOPATH
- CI jobs checking out directory to github.com/kubernetes/xyz

both resulting in problems with build, problems updating dependencies, sometimes things work on the dev environment and fail in CI causing folks to scratch their heads.

So let's standardize on the best practice "this git repo should be checked out under $GOPATH/src/k8s.io" and enforce it. Makefile will bail out when the directory is not correct (either because we checked out to the wrong repo, bad symlinks or wrong PWD)

### CODE REVIEW

**Comment by dims** [comment]
@flaper87 @j-griffith thanks for the support for this approach. Please lgtm

**Comment by kiwik** [comment]
OpenLab side PR https://github.com/theopenlab/openlab-zuul-jobs/pull/178

**Pull request merged**
