### PR TITLE
Test get listener protocol function [ Cloud Provider OpenStack ]

### PR DESCRIPTION
**Pull request by KingDaemonX**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```
implemented a testcase for the getListenerProtocol function to test all logic and possible outcome of the function, so as to prevent bug

### CODE REVIEW

**Comment by dulek** [comment]
Looks like you've combined two commits here. Can you make sure just one test is added in this PR by removing the `test : getSecurityGroupName` commit? `Test_getListenerProtocol()` looks good!

**Comment by KingDaemonX** [comment]
> Looks like you've combined two commits here. Can you make sure just one test is added in this PR by removing the `test : getSecurityGroupName` commit? `Test_getListenerProtocol()` looks good!

I just fixed the file issue that make the `getSecurityGroupName` code combine with the `Test_getListenerProtocol()` and make the push

thank you for you review and i hope it is all good now

**Pull request merged**
