### PR TITLE
Fix getting instance availability zone from Nova

### PR DESCRIPTION
**Pull request by lingxiankong**
**What this PR does / why we need it**:
Fix the code to set the correct availability zone for the instance, otherwide the pvc cannot bind to the pod because the zone doesn't match(using `ignore-volume-az=false`).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mogaika** [comment]
This pull request fixes #191?

**Comment by strigazi** [comment]
> This pull request fixes #191?

didn't work for me

**Comment by lingxiankong** [comment]
@mogaika yes, that's what this PR is trying to fix

@strigazi You still didn't see the az info in the node label during the CCM initialization? Please make sure the node has correct taint before you start CCM.

**Pull request merged**
