### PR TITLE
Add cloning via PVC annotation

### PR DESCRIPTION
**Pull request by aglitke**
This PR enables provisioning new volumes as a clone of an existing PVC.  To
request a clone, the user should add a clone request annotation to the PVC:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: clone-claim
  annotations:
    k8s.io/CloneRequest: default/source-pvc
```

The provisioner will locate the indicated PVC and determine the underlying
associated cinder volume ID.  The provisioner will use this ID as the
source-vol-id parameter when provisioning the new volume resulting in a clone
at the storage level.

Cloning will only work if the cinder backend supports "smart-cloning".  This
means that the clone will complete without the need for cinder to perform a
bit-for-bit copy using the host.  Because of this, the cinder provisioner will
not attempt to clone unless the associated storage class contains the
parameter: "smartclone" to indicate that volumes provisioned from this storage
class can be cloned correctly.

If the provisioner was able to clone the volume it will apply the
'k8s.io/CloneOf' annotation to the PVC.

### CODE REVIEW

**Comment by aglitke** [comment]
/cc @hogepodge 
Can you mark this one ok-to-test?

**Comment by zetaab** [comment]
if the cinder backend supports "smart-cloning" - how I can see does our cinder backend support this? Is this using basically volume clone command?

**Comment by aglitke** [comment]
@zetaab The short answer is "depends on the configuration".  I define "smart-cloning" as the ability to provision a new volume clone utilizing exclusively the storage backend.  When a source volume id is passed into the create verb cinder will request a clone from the backend storage if supported.  Otherwise, cinder will perform a host-assisted clone.  Host assisted clone is also needed when cloning across volume types.  Cinder host-assisted clone will obviously not work well in a kubernetes context so we want to avoid this.  This is why this patch requires the smartclone: true parameter to be added to the storage class being serviced by the provisioner.

**Comment by dims** [comment]
/approve
/lgtm

@aglitke please add some notes from here to the docs/

**Pull request merged**
