### PR TITLE
[cinder-csi-plugin] update topology feature docs

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
https://github.com/kubernetes-csi/external-provisioner/blob/v1.6.0/pkg/features/features.go#L38 , Topology feature doesnt seem to be enabled by default. So updating the docs.

xref: #1293
**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
Hmm...I found github automatically add `approved` label in the PRs submitted by the person who has approved permission.

**Comment by jichenjc** [comment]
@lingxiankong seems it's added recently, we should remove such auto label IMHO

**Comment by zetaab** [comment]
Thank you @ramineni

**Comment by ramineni** [comment]
> @lingxiankong seems it's added recently, we should remove such auto label IMHO

+1 , @lingxiankong any idea we could do that?

**Pull request merged**
