### PR TITLE
[manila-csi-plugin] Updated external-snapshotter to v2.1.1 and external-provisioner to v2.0.2 (release-1.19)

### PR DESCRIPTION
**Pull request by gman0**
This is a backport of https://github.com/kubernetes/cloud-provider-openstack/pull/1205 into the release-1.19 branch.

Cherry-picked from b59a3630c597dcf76e5193f17ff11eeee529020c

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by tombarron — APPROVED** [review]
Clean cherry pick.

**Comment by gman0** [comment]
PTAL @ramineni @brtknr

**Comment by gman0** [comment]
Do i need to set the release notes?

**Pull request merged**
