### PR TITLE
[1.27.3] 1.27.3 release

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

This PR bumps a release version for manifests and docs using a new `hack/bump-release.sh` script

**Special notes for reviewers**:

I adjusted the chart version manually to `2.27.5` in order to avoid linter errors.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by zetaab — APPROVED** [review]
/approve
/lgtm

**Comment by dulek** [comment]
/test openstack-cloud-controller-manager-e2e-test

Looks like k3s update breaks CI?

**Review by zetaab — APPROVED** [review]
/approve
/lgtm

/hold cancel

**Pull request merged**
