### PR TITLE
Run e2e Conformance tests on v1.12

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
Update zuul.yaml to run e2e Conformance tests on v1.12

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None.

**Special notes for your reviewer**:

**Release note**:
`NONE`.

````release-note
````

### CODE REVIEW

**Comment by adisky** [comment]
/cloud-provider-openstack-acceptance-test-e2e-conformance
/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12
/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.10

**Comment by dims** [comment]
/approve
/lgtm

/override openlab/cloud-provider-openstack-acceptance-test-flexvolume-cinder

**Pull request merged**
