### PR TITLE
Document cloning in the standalone-cinder provisioner

### PR DESCRIPTION
**Pull request by aglitke**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by zioproto** [comment]
You are proposing a PR with 3 commits that makes a bit of a mess in the git tree.
Could you make your branch `aglitke/doc-cloning` just a cherry-pick of commit `67e2bfdad8a06e5ac1e51c2931ce6a4ab3df75fb` on top of the current `origin/master` ?

If you push force this change to your local branch the PR will look much better.

The way you submit the PR at the moment you push into the git tree also commits like `6da022780d17d2c1759cdcaada786290777035c6` but the actual changes from this commit seem to be already merged in master long ago. 

thank you

**Comment by aglitke** [comment]
Alright, cleaned up the history @zioproto .

**Comment by hogepodge** [comment]
/approve
/lgtm

Why is the gate failing on this patch?

**Pull request merged**
