### PR TITLE
Add Lingxian Kong(lingxiankong) in reviewer list

### PR DESCRIPTION
**Pull request by lingxiankong**
I have been active developer in OpenStack projects (PTL of Qinling project), and we (Catalyst Cloud) are deploying Magnum in our OpenStack based public cloud, we are very interested in the integration between OpenStack and Kubernetes. We are willing to offer help.

### CODE REVIEW

**Comment by lingxiankong** [comment]
CLI signed

**Comment by hogepodge** [comment]
@lingxiankong please resolve conflicts. Also, if we can alphabetize the list it could help with preventing merge conflicts and keep it tidy.

Thanks!

**Comment by lingxiankong** [comment]
> @lingxiankong please resolve conflicts. Also, if we can alphabetize the list it could help with preventing merge conflicts and keep it tidy.

Hi Chris, I see you already submitted a patch to solve that, thanks!

**Comment by hogepodge** [comment]
Merged in #39 
Please close.

**Pull request closed without merging**
