### PR TITLE
Update Cinder CSI driver to 0.3.0

### LINKED ISSUE #242: Add Support for CSI Spec v0.3.0 in cinder CSI plugin
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
 CSI Spec v0.3.0 is released, needs to add support for it
https://github.com/container-storage-interface/spec/releases/tag/v0.3.0

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
This PR adds support for CSI v.0.3.0 in cinder CSI plugin
https://github.com/container-storage-interface/spec/releases/tag/v0.3.0

**Which issue this PR fixes** : 
fixes #242

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adi1712** [comment]
test cloud-provider-openstack-acceptance-test-csi-cinder, is failing from external provisioner update 2.1
https://github.com/kubernetes-csi/external-provisioner/blob/v0.2.1/pkg/controller/controller.go
In zuul we are building docker image from latest code, but it is pointing tp 2.0 image in cinder csi manifests

**Comment by adisky** [comment]
test cloud-provider-openstack-acceptance-test-csi-cinder, is failing from external provisioner update 2.1
https://github.com/kubernetes-csi/external-provisioner/blob/v0.2.1/pkg/controller/controller.go
In zuul we are building external provisioner docker image from latest code, but it is pointing to 2.0 image in cinder csi manifests
https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml

**Pull request merged**
