### PR TITLE
[cinder-csi-plugin] Enable volume expansion and volume cloning e2e tests

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
This PR enables volume expansion and volume cloning tests.
**Which issue this PR fixes(if applicable)**:
fixes #1655

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ramineni** [comment]
@lingxiankong Im wondering why this job openlab/cloud-provider-openstack-e2e-test-csi-cinder is still running , when its not enabled in .zuul.yaml ?

**Comment by ramineni** [comment]
@lingxiankong devstack is failing with below error. Any idea? 
`fatal: unable to access 'https://opendev.org/openstack/devstack/': server certificate verification failed. CAfile: none CRLfile: none`

**Comment by lingxiankong** [comment]
> @lingxiankong Im wondering why this job openlab/cloud-provider-openstack-e2e-test-csi-cinder is still running , when its not enabled in .zuul.yaml ?

There is one more thing we need to remove from the zuul config. Will do that.

**Comment by lingxiankong** [comment]
/override openlab/cloud-provider-openstack-e2e-test-csi-cinder

**Comment by jichenjc** [comment]
>>>Why was manila-e2e triggered?
https://github.com/kubernetes/test-infra/blob/b821c8aa44bc774fb21b85ffa9fcae3404a442f5/config/jobs/kubernetes/cloud-provider-openstack/provider-openstack-presubmits-release-master-config.yaml#L82

yeah.. looks weird, I am also curious ,is it possible that we can check the test-infra logs to see why
it's triggered?

**Comment by ramineni** [comment]
> > > > Why was manila-e2e triggered?
> > > > https://github.com/kubernetes/test-infra/blob/b821c8aa44bc774fb21b85ffa9fcae3404a442f5/config/jobs/kubernetes/cloud-provider-openstack/provider-openstack-presubmits-release-master-config.yaml#L82
> 
> yeah.. looks weird, I am also curious ,is it possible that we can check the test-infra logs to see why it's triggered?

job looks ok to me as well. No idea why manila job getting triggered. @lingxiankong Any idea?

**Comment by ramineni** [comment]
@lingxiankong PTAL ^^

**Comment by ramineni** [comment]
Again openstack-cloud-keystone-authentication-authorization-test got triggered on irrelevant files . Looks like regex should be changed I suppose.

**Comment by ramineni** [comment]
/override openstack-cloud-keystone-authentication-authorization-test

**Pull request merged**
