### PR TITLE
[cinder-csi-plugin] bump CSI sidecar versions to latest 

### PR DESCRIPTION
**Pull request by jichenjc**
only noticable change is RBAC update of snapshoter
by refering to
https://github.com/kubernetes-csi/external-snapshotter/pull/526/files

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by ramineni** [comment]
@jichenjc Thanks. Looks good to me . modified title little bit.

Could you update the release notes with supported versions , might be helpful for users?

**Comment by jichenjc** [comment]
@ramineni updated, I guess no need list every version of side car?

**Comment by ramineni** [comment]
> @jichenjc latest version seems ambiguous as by the time 1.24 is released, latest versions might be different. Its better to update the versions we support IMO.

@jichenjc updated release notes a bit. let me know if that looks ok to you.

**Comment by jichenjc** [comment]
>>>@jichenjc updated release notes a bit. let me know if that looks ok to you.

@ramineni sorry, missed this :( 
thanks for the update, lgtm

**Comment by lingxiankong** [comment]
> Could you update the release notes with supported versions , might be helpful for users?

I've removed the release note, as just say we've upgrade from version X to version Y doesn't help the user to understand what happened, rather, e.g. we upgrade the version again in this release, we will have another release note saying we've upgraded from version Y to version Z, which may lead to confusion for the users.

**Comment by lingxiankong** [comment]
I'm not sure why the job openstack-cloud-controller-manager-e2e-conformance-test is running for this PR?

**Comment by lingxiankong** [comment]
/override openstack-cloud-controller-manager-e2e-conformance-test

**Pull request merged**
