### PR TITLE
Update defaultMetadataVersion to latest

### PR DESCRIPTION
**Pull request by ramineni**
Currently defaultMetadataVersion is set to 2012-08-10 which is
very old. This commit updates the same.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by adisky** [comment]
we can use latest one, as pointed out in openstack docks
https://docs.openstack.org/nova/rocky/user/metadata-service.html
/lgtm

**Comment by jichenjc** [comment]
seems no reason not to use latest
/lgtm

**Pull request merged**
