### PR TITLE
[octavia-ingress-controller] Improve Ingress reconciliation

### PR DESCRIPTION
**Pull request by lingxiankong**
**What this PR does / why we need it**:
Cherry picked from https://github.com/kubernetes/cloud-provider-openstack/pull/1418

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:
```release-note
[octavia-ingress-controller] Fixed the issue that pools and l7 policies are removed no matter how the Ingress is changed.
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
Error msg for job cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.18 when joining the worker node to the cluster:
```
2021-03-09 10:21:48.690256 | k8s-node-2 | error execution phase preflight: couldn't validate the identity of the API Server: Get https://192.168.0.4:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: dial tcp 192.168.0.4:6443: connect: no route to host
```

**Comment by lingxiankong** [comment]
Failed with the same error.

**Comment by ramineni** [comment]
/lgtm
/approve

Failure doesnt seem to be related.

**Comment by lingxiankong** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.18

**Pull request merged**
