### PR TITLE
Get a token using Keystone Application Credential

### LINKED ISSUE #232: Using k8s-keystone-auth with OpenStack Application Credentials
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

The k8s-keystone-auth component requires some values to be set from the user in the OS env.

**What you expected to happen**:

It should be very useful in order to simplify the user experience adding support also to the Application Credentials (https://docs.openstack.org/keystone/queens/user/application_credentials.html) OpenStack authentication.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zioproto**
**What this PR does / why we need it**:

This PR makes possibile to login using Keystone Application Credentials.
fixes #232 

**Special notes for your reviewer**:

This PR requires this gophercloud PR to be merged first 
https://github.com/gophercloud/gophercloud/pull/1224

### CODE REVIEW

**Comment by zioproto** [comment]
@rdl87 make sure you test commit b59d23d . thanks

**Comment by zioproto** [comment]
The gophercloud patch was merged upstream:

**Comment by zioproto** [comment]
I had to modify also the `Gopkg.lock` file to make sure the latest version of gophercloud is installed by `dep`. Not sure why we committed the `Gopkg.lock`. Me might consider dropping this in the future. Thanks.

**Comment by kiwik** [comment]
Hi @zioproto, just the csi cinder job failed, you can only retrigger that job with comment `/test cloud-provider-openstack-acceptance-test-csi-cinder`, see more details in https://github.com/theopenlab/cicd-howto/blob/master/README.md#kubernetescloud-provider-openstack , and if you need to check test logs, you can find them in URL https://github.com/kubernetes/cloud-provider-openstack/pull/282#issuecomment-422319206

**Comment by dims** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-csi-cinder

**Comment by dims** [comment]
@zioproto sorry too so long to get back to this PR. Can you please rebase?

**Comment by dims** [comment]
Gah. i made it worse, @zioproto can you please undo the changes to Gopkg.lock in this PR?

**Comment by zioproto** [comment]
I rebased on the current `master`. Let's see if the tests pass now 👍

**Pull request merged**
