### PR TITLE
[occm] add priorityClassName to helm chart

### PR DESCRIPTION
**Pull request by iceman2077**
**What this PR does / why we need it:**
ability to add priority class for occm 

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mdbooth** [comment]
/ok-to-test

Not that I think these have test coverage?

**Comment by iceman2077** [comment]
> /ok-to-test
> 
> Not that I think these have test coverage?

I didn't see that here were tests for the helm chart

**Comment by jichenjc** [comment]
>>>I didn't see that here were tests for the helm chart

IIRC there is no helm chart test ..

**Comment by dulek** [comment]
/lgtm

Makes perfect sense to me.

**Pull request merged**
