### PR TITLE
Backport https://github.com/kubernetes/cloud-provider-openstack/pull/2237

### PR DESCRIPTION
**Pull request by cwrau**
I hope this is correct 😅

Originated from https://github.com/kubernetes/cloud-provider-openstack/issues/2364

```release-note
NONE
```

### CODE REVIEW

**Comment by dulek** [comment]
/ok-to-test

Thanks, this looks good! I'll edit PR description to readd the release note [from the template](https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by dulek** [comment]
```
WARNING: The elapsed duration (-5s) is negative. This can be caused by another process outside of Prow writing into the finished.json file. The file currently has a completion time of 2023-09-19 12:13:18 +0000 UTC.
```
/retest

**Comment by cwrau** [comment]
Awesomesauce, thank you 👍

**Pull request merged**
