### PR TITLE
Update .zuul.yaml with correct job name

### PR DESCRIPTION
**Pull request by mrhillsman**
Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>

### CODE REVIEW

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
@dims @hogepodge apologies I do not know the correct workflow to get this merged but I have confirmed this change is needed; also note theopenlab-ci bot replies NODE_FAILURE then SUCCESS

**Comment by dims** [comment]
@mrhillsman the commit has "[DNM]", want to remove that? (looks like PR title you fixed already)

**Comment by mrhillsman** [comment]
@dims commit message updated, thx

**Pull request merged**
