### PR TITLE
Add `auth-type` as input param

### LINKED ISSUE #1124: [all] no AuthType provided in openstack connection
/kind feature

**What happened**:
need honor `auth-type` so that we can change method to auth from cloud provider to openstack

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #1124 

**Special notes for reviewers**:

**Release note**:

```release-note
auth-type can be input as param to auth from provider to openstack 
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
Hi, what if we don't specify `auth-type` but provide configs like `application-credential-id` and `application-credential-secret`, will the authentication will fail?

**Comment by kayrus** [comment]
> Hi, what if we don't specify auth-type but provide configs like application-credential-id and application-credential-secret, will the authentication will fail?

@lingxiankong no, it won't

**Comment by lingxiankong** [comment]
> > Hi, what if we don't specify auth-type but provide configs like application-credential-id and application-credential-secret, will the authentication will fail?
> 
> @lingxiankong with the current master branch, no, it won't. with this change - probably yes.

Thanks @kayrus, so is it necessary to add the extra `auth-type` config option?

**Comment by jichenjc** [comment]
@kayrus @lingxiankong from my test, if didn't change auth-type, the auth will fail
maybe I used wrong configuration before... so I will redo my test and paste result here

**Comment by kayrus** [comment]
@lingxiankong I never had issues with auth. app creds works, password auth works.

**Comment by jichenjc** [comment]
I think I misunderstood the logic

gophercloud handles the logic for us https://github.com/gophercloud/gophercloud/blob/master/auth_options.go#L224
so we should close this PR

**Pull request closed without merging**
