### PR TITLE
Load balancer class support via .Values.cloudConfigContents to be passed inside secret.yaml

### PR DESCRIPTION
**Pull request by zakthan**
Just pass a values.yaml containing a .Values.cloudConfigContents field

For example:

```

cloudConfigContents: |
         [Global]
         auth-url=""
         username=""
         user-domain-id=""
         password=""
         tenant-id=""
         project-domain-name=""
         region=""
         ca-file=""
         [Networking]
         internal-network-name=""
         [LoadBalancer]
         enable-ingress-hostname="true"
         use-octavia="true"
         create-monitor="true"
         floating-network-id=""
         subnet-id=""
         [LoadBalancerClass "testclass"]
         floating-network-id = ""
         subnet-id = ""
         [BlockStorage]
         ignore-volume-az=""
```

### CODE REVIEW

**Comment by jichenjc** [comment]
please sign CNCF first so system will auto remove your cncf-no flag .. thanks~

**Comment by zakthan** [comment]
will reopen

**Comment by zakthan** [comment]
> please sign CNCF first so system will auto remove your cncf-no flag .. thanks~
@jichenjc sorry I had issues with this one. Olz check new one:
https://github.com/kubernetes/cloud-provider-openstack/pull/1953

**Pull request closed without merging**
