### PR TITLE
Volunteer to review and collaborate

### PR DESCRIPTION
**Pull request by flaper87**
As promised, I'm putting my name out there to help review and maintain this cloud provider.

I'm not sure what the right process to update `OWNERS` is but here's a try :)

### CODE REVIEW

**Comment by rootfs** [comment]
@flaper87 @dims my pleasure to help too

**Comment by dims** [comment]
@rootfs please file a PR against OWNERS file and thanks!

**Comment by rootfs** [comment]
@dims will do after this one merged

any more volunteers I can add?

**Comment by dims** [comment]
@rootfs i'd prefer folks to volunteer on their own (separate PRs) for now.

**Comment by hogepodge** [comment]
Since there's a conflict, being explicit in the PR title and description about who is being added will aid in history. Me is ambiguous, but flaper87 contains much more meaning.

**Comment by hogepodge** [comment]
Merged in #39.
Please close.

**Comment by flaper87** [comment]
thanks

**Pull request closed without merging**
