### PR TITLE
[occm] Remove volume related code from occm

### PR DESCRIPTION
**Pull request by lingxiankong**
**What this PR does / why we need it**:
Remove volume related code from openstack-cloud-controller-manager. The code was initially moved from k8s in-tree code, but the volume related functions were never provided by occm, especially the cinder-csi-plugin is the way to go.

What's more, removing the code also deletes the volume related unit test from cloud-provider-openstack-unittest job, which always causes CI issues.

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
@ramineni ready for review

**Comment by ramineni** [comment]
Thanks.
/lgtm

**Comment by ramineni** [comment]
To fix quota issues , merging this
/approve

**Pull request merged**
