### PR TITLE
[release-1.28] [occm] Make sure we don't mask LB tests failures and fix what was failing

### PR DESCRIPTION
**Pull request by dulek**
This is a cherry-pick of #2360

```release-note
NONE
```

/hold

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Clean cherry-pick.
/lgtm

**Comment by dulek** [comment]
/retest

This is very weird.

**Comment by dulek** [comment]
#2542

But locally all works. :/

**Comment by mandre** [comment]
It's clearly not caused by your PR as we had a bunch of the same failure yesterday, both in `release-1.28` and `master`: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cloud-provider-openstack-check

https://github.com/kubernetes/cloud-provider-openstack/pull/2542 shows that it can work, however I'm surprised that it suddenly broke as the previous version was working fine until now. Perhaps there's a new dep that it doesn't like?

Let's see one last time if it fixed by itself.
/retest

**Comment by mandre** [comment]
The test image is different between a failing job and a working one: [`gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240130-9db6d59ca0-master`](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/2537/pull-cloud-provider-openstack-check/1755486021669097472/podinfo.json) vs [`gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240111-cf1d81388e-master`](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/2536/pull-cloud-provider-openstack-check/1755227542530297856/podinfo.json).

I suspect different versions of go that break golangci-lint.

**Comment by mandre** [comment]
Bingo!

```
❯ podman run --rm --entrypoint /usr/local/go/bin/go gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240111-cf1d81388e-master version
go version go1.21.6 linux/amd64


❯ podman run --rm --entrypoint /usr/local/go/bin/go gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240130-9db6d59ca0-master version
go version go1.22rc2 linux/amd64
```

And https://github.com/golangci/golangci-lint/pull/4272

This explains why we need [the newest version of golangci-lint](https://github.com/golangci/golangci-lint/releases/tag/v1.56.0).

**Pull request merged**
