### PR TITLE
Prettify identity code

### PR DESCRIPTION
**Pull request by Fedosin**
This patch makes the code look better and conform to the standards of the go language.

1. All variables var_name were renamed to varName.
2. Comments were added for all public facing entities.
3. Entities that are not used outside of the module were declared as private.
4. Several small typos were fixed as well.

### CODE REVIEW

**Comment by dims** [comment]
looks good, looks like one failure

**Comment by Fedosin** [comment]
Yeah, I just rebased on master

**Comment by hogepodge** [comment]
Thanks for the updates.

/approve

**Pull request merged**
