### PR TITLE
[occm] Make sure we don't mask LB tests failures and fix what was failing

### PR DESCRIPTION
**Pull request by dulek**
**What this PR does / why we need it**:
In `test-lb-service.sh` we do `trap "delete_resources" EXIT` to make sure we cleanup resources on a test failure. In there, we only fetched the `$?` after making a check for `${AUTO_CLEAN_UP}`, which itself alters the code to 0, so function always returns success. This means tests can never really fail.

This commit fixes it by making sure `$ERROR_CODE` is fetched at the very beginning of the cleanup function.

Some additional fixes needed to be made to make tests passing again. In particular:
* Tests no longer create Services as internal in order to make shared LB tests work after #2190.
* FIP is added to the user LB in the sharing test in order for CPO to not complain about not being able to create it for a secondary Service.

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dulek** [comment]
This is a backport of testing fixes into release-1.27. I'll need to add it to earlier releases too.

**Comment by dulek** [comment]
I forced-rebased this, let's see.

**Comment by dulek** [comment]
Yup, looks good now!

**Comment by dulek** [comment]
@jichenjc, @kayrus, @zetaab, care for a `/lgtm` here?

**Comment by dulek** [comment]
@jichenjc, @kayrus, @zetaab, care for a /lgtm here?

**Review by zetaab — APPROVED** [review]
/lgtm

**Pull request merged**
