### PR TITLE
WIP: [all] update openstack providerID check

### LINKED ISSUE #1186: [all] Fix ProviderID "xxxx" didn't match expected format "openstack:///InstanceID
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

ProviderID "openstack://ubuntu-xenial-citynetwork-citynetwork-openlab-0000146249" didn't match expected format "openstack:///InstanceID

is reported in logs , we need handle it 

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #1186 

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
seems still related to node issue

```
I0907 03:55:46.817873   11719 scheduling_queue.go:812] About to try and schedule pod kube-system/csi-cinder-controllerplugin-0
I0907 03:55:46.817938   11719 scheduler.go:452] Attempting to schedule pod: kube-system/csi-cinder-controllerplugin-0
I0907 03:55:46.818022   11719 factory.go:443] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="kube-system/csi-cinder-controllerplugin-0"
I0907 03:55:46.818242   11719 scheduler.go:347] Updating pod condition for kube-system/csi-cinder-controllerplugin-0 to (PodScheduled==False, Reason=Unschedulable)
I0907 03:56:46.818464   11719 scheduling_queue.go:812] About to try and schedule pod kube-system/csi-cinder-controllerplugin-0
I0907 03:56:46.818533   11719 scheduler.go:452] Attempting to schedule pod: kube-system/csi-cinder-controllerplugin-0
I0907 03:56:46.818628   11719 factory.go:443] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="kube-system/csi-cinder-controllerplugin-0"
I0907 03:56:46.818793   11719 scheduler.go:347] Updating pod condition for kube-system/csi-cinder-controllerplugin-0 to (PodScheduled==False, Reason=Unschedulable)
I0907 03:57:46.818911   11719 scheduling_queue.go:812] About to try and schedule pod kube-system/csi-cinder-controllerplugin-0
I0907 03:57:46.818972   11719 scheduler.go:452] Attempting to schedule pod: kube-system/csi-cinder-controllerplugin-0
I0907 03:57:46.819052   11719 factory.go:443] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="kube-system/csi-cinder-controllerplugin-0"
I0907 03:57:46.819201   11719 scheduler.go:347] Updating pod condition for kube-system/csi-cinder-controllerplugin-0 to (PodScheduled==False, Reason=Unschedulable)
```

schedule mentioned no nodes are available

**Review by zetaab — COMMENTED** [review]
before just forcing `///` -> `//` we should think compatibility. I know that this old format is used in many places, so if you just change it, it will break everything

**Comment by jichenjc** [comment]
ok, let's use this to do further test and when find the root cause, we can switch back ..

I already found this in the PR, maybe related ..
```
E0907 03:52:57.703170   11717 node_lifecycle_controller.go:155] error checking if node ubuntu-xenial-citynetwork-citynetwork-openlab-0000146536 is shutdown: Resource not found
I0907 03:52:57.712153   11717 node_lifecycle_controller.go:181] deleting node since it is no longer present in cloud provider: ubuntu-xenial-citynetwork-citynetwork-openlab-0000146536
I0907 03:52:57.714100   11717 event.go:278] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ubuntu-xenial-citynetwork-citynetwork-openlab-0000146536", UID:"2a6759ba-3952-468b-9110-335735225bdd", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Deleting node ubuntu-xenial-citynetwork-citynetwork-openlab-0000146536 because it does not exist in the cloud provider' Node ubuntu-xenial-citynetwork-citynetwork-openlab-0000146536 event: DeletingNode
```

**Pull request closed without merging**
