### PR TITLE
Update docker image version

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
update docker image version in manifests to v1.16

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kayrus** [comment]
Is it ok when the version command returns:

```sh
docker run --rm -ti docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.16.0 /bin/openstack-cloud-controller-manager --version
Kubernetes v0.0.0-master+$Format:%h$
```
?

**Comment by ramineni** [comment]
@adisky This needs to be merged after the release right?

**Comment by adisky** [comment]
@ramineni yes, the PR is open against release-1.16 branch

**Comment by ramineni** [comment]
> @ramineni yes, the PR is open against release-1.16 branch

Ah, right. Sorry missed it. Thanks
/lgtm

**Comment by adisky** [comment]
merging this, as failures are not related, and need to make v1.16 release

**Pull request merged**
