### PR TITLE
Allow to specify default value in cloud-config for openstack-internal…

### PR DESCRIPTION
**Pull request by JrCs**
…-load-balancer

Signed-off-by: JrCs <90z7oey02@sneakemail.com>

**What this PR does / why we need it**:
Add on option (`internal-lb`) in the cloud-config configuration file so we can set the default value for openstack-internal-load-balancer

### CODE REVIEW

**Comment by lingxiankong** [comment]
Why we need this? We already have the `service.beta.kubernetes.io/openstack-internal-load-balancer` annotation which could do the same thing, and it's flexible. I didn't see this PR brings much value here.

**Comment by lingxiankong** [comment]
/hold

Wait for author's response.

**Comment by JrCs** [comment]
@lingxiankong Yes we can use the `service.beta.kubernetes.io/openstack-internal-load-balancer` annotation to change the behavior for a particular service. But by default a floating IP is always created if you don't specify the annotation.
In my company we do not use an internal openstack network for the VM but 2 "external" networks: 1 for the VM and 1 for the VIP of loadbalancer. So in our case we don't want to create a floationg IP for every service.
So the solution to not create an annotation for EVERY service to disable the creation of floating IP is to have an option to change the **default** value of the  `openstack-internal-load-balancer` option.
I any case the **default** value can be overwritten by an annotation.

**Comment by JrCs** [comment]
Is it ok for you ?

**Comment by lingxiankong** [comment]
i'm ok with this change, please rebase your commit and make sure all tests are passed.

**Comment by lingxiankong** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
