### PR TITLE
octavia-ingress-controller: Fix the floating ip description

### LINKED ISSUE #460: octavia-ingress-controller: Incorrect description for load balancer vip floating IP
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug

**What happened**:
After creating an ingress named `test-octavia-ingress` in `default` namespace, the load balancer vip floating ip description shows:
`Floating IP for Kubernetes ingress default in namespace test-octavia-ingress from cluster 5be2a4b2-a10a-4991-b9a7-db3e9cb79d07`

**What you expected to happen**:
Should be ``Floating IP for Kubernetes ingress test-octavia-ingress in namespace default from cluster 5be2a4b2-a10a-4991-b9a7-db3e9cb79d07``

### PR DESCRIPTION
**Pull request by lingxiankong**
**What this PR does / why we need it**:
Fix the the load balancer vip floating ip description, mainly changed EnsureFloatingIP method parameters order.

**Which issue this PR fixes** : 
fixes #460

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by ramineni** [comment]
@lingxiankong Thanks. looks good. May be you could change the PR heading / description to "fix EnsureFloatingIP parameters order" ... as they are passed wrongly currently.

**Comment by lingxiankong** [comment]
> @lingxiankong Thanks. looks good. May be you could change the PR heading / description to "fix EnsureFloatingIP parameters order" ... as they are passed wrongly currently.

Thanks for the advice!

**Comment by lingxiankong** [comment]
/approve

Merge it given it's a trivial patch

**Pull request merged**
