### PR TITLE
Add v1.15 release job and remove v1.12 job

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
Add v1.15 release job and remove v1.12 job

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kiwik** [comment]
Have to restart zuul to apply the new pipelines, I will recheck the PR when OpenLab side is ready.

**Comment by adisky** [comment]
@kiwik Thanks

**Comment by ramineni** [comment]
Thanks. Job failure seems to be again memory issue
/lgtm

**Comment by hogepodge** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance
/lgtm

**Comment by hogepodge** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.12

**Pull request merged**
