### PR TITLE
New options validator for manila-provisioner

### PR DESCRIPTION
**Pull request by gman0**
**What this PR does / why we need it**:
Revamp of the previous version of the options validator: cleaner code, easier testing, added a few internal features - this will make https://github.com/kubernetes/cloud-provider-openstack/issues/420 a lot easier to implement with proper input validation

Makes following code no longer necessary as we'll get valid input every time:
https://github.com/kubernetes/cloud-provider-openstack/blob/a63c14dd484381995562dc8c02861b5c557e60db/pkg/share/manila/sharebackends/csicephfs.go#L41-L43

Fixes a bug described here https://github.com/kubernetes/cloud-provider-openstack/pull/370#discussion_r236616224

https://github.com/kubernetes/cloud-provider-openstack/commit/9c066a03ec19d64db7c29729cfc7dc0aa3bc90f8 : unrelated, but the newer version of `external-storage` lib in this repo breaks the deployment because leader election requires access to `endpoints` - this commit fixes it. Hopefully it can be squeezed into this PR.

**Release note**:

```release-note
manila-provisioner: shareSecretNamespace option now defaults to "default" (as opposed to coalescing with osSecretNamespace)
```

### CODE REVIEW

**Comment by dims** [comment]
/hold

needs rebase

**Comment by gman0** [comment]
@dims finally passing CI, PTAL

I've added one more commit here https://github.com/kubernetes/cloud-provider-openstack/pull/443/commits/ef56215b90cac0cf92d1f750f2ab2e88e2ec01d5 - turns out I was a bit too hasty with accepting case-insensitive inputs. The `protocol` field still can accept case-insensitive values though, since Manila doesn't care either:

https://github.com/openstack/manila/blob/3017c3239e5056a1cfc992e91bd822baaa589940/manila/share/api.py#L129-L138

**Pull request merged**
