### PR TITLE
[WIP] Dummy PR for testing CI jobs

### PR DESCRIPTION
**Pull request by dims**
Just testing...

### CODE REVIEW

**Comment by dims** [comment]
w00t! only 4 failures

```
2018-04-07 02:04:22.336697 | ubuntu-xenial-vexxhost | [91m[1mSummarizing 4 Failures:[0m
2018-04-07 02:04:22.336734 | ubuntu-xenial-vexxhost |
2018-04-07 02:04:22.336956 | ubuntu-xenial-vexxhost | [91m[1m[Fail] [0m[90m[sig-api-machinery] Downward API [0m[91m[1m[It] should provide host IP as an env var  [Conformance] [0m
2018-04-07 02:04:22.337149 | ubuntu-xenial-vexxhost | [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2302[0m
2018-04-07 02:04:22.337185 | ubuntu-xenial-vexxhost |
2018-04-07 02:04:22.337382 | ubuntu-xenial-vexxhost | [91m[1m[Fail] [0m[90m[sig-network] DNS [0m[91m[1m[It] should provide DNS for the cluster  [Conformance] [0m
2018-04-07 02:04:22.337589 | ubuntu-xenial-vexxhost | [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:421[0m
2018-04-07 02:04:22.337629 | ubuntu-xenial-vexxhost |
2018-04-07 02:04:22.337905 | ubuntu-xenial-vexxhost | [91m[1m[Fail] [0m[90m[sig-cli] Kubectl client [0m[0m[k8s.io] Guestbook application [0m[91m[1m[It] should create and stop a working application  [Conformance] [0m
2018-04-07 02:04:22.338151 | ubuntu-xenial-vexxhost | [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1910[0m
2018-04-07 02:04:22.338200 | ubuntu-xenial-vexxhost |
2018-04-07 02:04:22.338373 | ubuntu-xenial-vexxhost | [91m[1m[Fail] [0m[90m[k8s.io] Pods [0m[91m[1m[It] should get a host IP  [Conformance] [0m
2018-04-07 02:04:22.338582 | ubuntu-xenial-vexxhost | [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:67[0m
2018-04-07 02:04:22.338627 | ubuntu-xenial-vexxhost |
2018-04-07 02:04:22.338738 | ubuntu-xenial-vexxhost | [1m[91mRan 162 of 881 Specs in 5763.712 seconds[0m
2018-04-07 02:04:22.357116 | ubuntu-xenial-vexxhost | [1m[91mFAIL![0m -- [32m[1m158 Passed[0m | [91m[1m4 Failed[0m | [33m[1m0 Pending[0m | [36m[1m719 Skipped[0m --- FAIL: TestE2E (5763.78s)
```

**Comment by kiwik** [comment]
Hi @dims , I add a separated pipeline in OpenLab side https://github.com/theopenlab/openlab/issues/45 , with that we can trigger e2e conformance test by using comment **/test cloud-provider-openstack-e2e-conformance**, and we should update .zuul.yaml, like this, hope to help:
```yaml
- project:
    cloud-provider-openstack-all:
      jobs:
        - cloud-provider-openstack-unittest
        - cloud-provider-openstack-acceptance-test-keystone-authentication-authorization
        - cloud-provider-openstack-acceptance-test-lb-octavia
        - cloud-provider-openstack-acceptance-test-e2e-conformance
    cloud-provider-openstack-unit:
      jobs:
        - cloud-provider-openstack-unittest
    cloud-provider-openstack-lb:
      jobs:
        - cloud-provider-openstack-acceptance-test-lb-octavia
    cloud-provider-openstack-auth:
      jobs:
        - cloud-provider-openstack-acceptance-test-keystone-authentication-authorization
    cloud-provider-openstack-e2e-conformance:
      jobs:
        - cloud-provider-openstack-acceptance-test-e2e-conformance
```

**Comment by dims** [comment]
Down to 2 failures : 

```
2018-04-08 04:13:22.338323 | ubuntu-xenial-vexxhost | [91m[1mSummarizing 2 Failures:[0m
2018-04-08 04:13:22.338355 | ubuntu-xenial-vexxhost |
2018-04-08 04:13:22.338520 | ubuntu-xenial-vexxhost | [91m[1m[Fail] [0m[90m[sig-cli] Kubectl client [0m[0m[k8s.io] Guestbook application [0m[91m[1m[It] should create and stop a working application  [Conformance] [0m
2018-04-08 04:13:22.338663 | ubuntu-xenial-vexxhost | [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1910[0m
2018-04-08 04:13:22.338698 | ubuntu-xenial-vexxhost |
2018-04-08 04:13:22.338832 | ubuntu-xenial-vexxhost | [91m[1m[Fail] [0m[90m[sig-network] DNS [0m[91m[1m[It] should provide DNS for the cluster  [Conformance] [0m
2018-04-08 04:13:22.338956 | ubuntu-xenial-vexxhost | [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:421[0m
2018-04-08 04:13:22.338993 | ubuntu-xenial-vexxhost |
2018-04-08 04:13:22.339069 | ubuntu-xenial-vexxhost | [1m[91mRan 162 of 881 Specs in 5060.942 seconds[0m
```
http://logs.openlabtesting.org/logs/92/92/f70eec854b8711ccb3d37465217598a891fe17a2/cloud-provider-openstack-all/cloud-provider-openstack-acceptance-test-e2e-conformance/ffe99c1/job-output.txt.gz

**Comment by dims** [comment]
Done with this now.

**Pull request closed without merging**
