### PR TITLE
Change default az to empty when create cinder volume

### LINKED ISSUE #72: Create cinder volume failed with default availability zone 'nova'
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
create cinder volume failed against a specific cloud provider due to invalid parameters caused by incorrect availability zone, because the default value of 'nova' [1] in this repository doesn't match the real case in cloud provider.

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/volume/cinder/volumeservice/actions.go#L75

**What you expected to happen**:
create cinder volume succeed by change the default value of availability zone to empty.

**How to reproduce it (as minimally and precisely as possible)**:
1. install openstack cinder standalone service
2. create a k8s cluster via local-up-cluster.sh
3. run the cinder-provisioner binary built from this repository
4. run test from this repository, kubectl apply -f examples/persistent-volume-provisioning/cinder/cinder-full.yaml

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: latest
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): Linux 4.4.0-116-generic
- Install tools: git, make
- Others:

### PR DESCRIPTION
**Pull request by animationzl**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #72 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by animationzl** [comment]
signed

**Comment by dims** [comment]
@zetaab Note that this is the new external volume service, not the regular cinder one from the main k/k. So no one is using this yet.

**Comment by zetaab** [comment]
@dims ok but still I would like to get answer how it behaves if az is empty.

**Comment by dims** [comment]
@animationzl please respond to @zetaab 's question

**Comment by animationzl** [comment]
@zetaab yes, the cloud provider I use has a different az name than nova, the default az in cinder create api is None, when creating volume without a specific az(such as `cinder create 1`), a random az of specific volume host which the volume is scheduled to will be chose as result.

**Comment by zetaab** [comment]
ok then I can approve that change :)

**Comment by zetaab** [comment]
/approve

@dims add LGTM if you think this is ok to merge

**Pull request merged**
