### PR TITLE
[WIP]: fix k3s installation issue

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

add cloudbuild.yaml from the master branch

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
add cloudbuild.yaml from the master branch
```

### CODE REVIEW

**Comment by zetaab** [comment]
this is not enough, you need to modify a lot more files. Like Makefile, dockerfiles etc. I did not cherry pick these changes because it is too much for old releases.

**Comment by kayrus** [comment]
@zetaab can we use old-style build CI?

**Comment by zetaab** [comment]
we can still use old CI for release-1.26 and older. The problem that I see is that we did like 10+ PRs to make release-1.27 and master to work with that. So I am pretty sure that if these are merged, the release branch will be broken after that.

**Comment by kayrus** [comment]
> we can still use old CI for release-1.26 and older. The problem that I see is that we did like 10+ PRs to make release-1.27 and master to work with that. So I am pretty sure that if these are merged, the release branch will be broken after that.

can we at least give it a try?

**Comment by kayrus** [comment]
1.25 is outdated

**Pull request closed without merging**
