### PR TITLE
test for getboolfromserviceannotationfunction

### PR DESCRIPTION
**Pull request by FavourEva**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dulek** [comment]
/ok-to-test

Nice! Can you switch this to a format with multiple testcases in a loop like here [1]? Also looks like you've removed the release note box from the PR description, you got to add it back. See the template: [2].

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/45d239088c53cdd1a860278fba807e6f8362945e/pkg/openstack/loadbalancer_test.go#L455-L461
[2] https://github.com/kubernetes/cloud-provider-openstack/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by FavourEva** [comment]
> /ok-to-test
> 
> Nice! Can you switch this to a format with multiple testcases in a loop like here [1]? Also looks like you've removed the release note box from the PR description, you got to add it back. See the template: [2].
> 
> [1]
> 
> https://github.com/kubernetes/cloud-provider-openstack/blob/45d239088c53cdd1a860278fba807e6f8362945e/pkg/openstack/loadbalancer_test.go#L455-L461
> 
> 
> [2] https://github.com/kubernetes/cloud-provider-openstack/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Okay, would add it back right away and work on the format. Thanks alot

**Review by FavourEva — COMMENTED** [review]
switched to a format with multiple testcases in a loop

**Pull request closed without merging**
