### PR TITLE
[occm] add secret enabled option

### PR DESCRIPTION
**Pull request by simonostendorf**
**What this PR does / why we need it**:

This PR adds the abbility to disable the secret mount into the daemonset. 
This allows to mount the secrets with init-containers (like vault-agent-injector). 

**Which issue this PR fixes(if applicable)**:
none

**Special notes for reviewers**:

**Release note**:

```release-note
[openstack-cloud-controller-manager] add secret enabled option
```

### CODE REVIEW

**Comment by jichenjc** [comment]
please check https://github.com/kubernetes/cloud-provider-openstack/pull/2237#pullrequestreview-1417420755 as well

**Comment by simonostendorf** [comment]
> please check [#2237 (review)](https://github.com/kubernetes/cloud-provider-openstack/pull/2237#pullrequestreview-1417420755) as well

done, using same version as mentioned before

**Review by zetaab — APPROVED** [review]
/approve

**Comment by jichenjc** [comment]
✖︎ openstack-cloud-controller-manager => (version: "2.28.0-alpha.4", path: "charts/openstack-cloud-controller-manager") > chart version not ok. Needs a version bump! 

@simonostendorf can you update to newer version so we can get this merged? Thanks

**Comment by simonostendorf** [comment]
> @simonostendorf can you update to newer version so we can get this merged? Thanks

done

**Comment by dulek** [comment]
Linter fails on trailing whitespace here. Can you fix this and I'll /lgtm it?

**Comment by simonostendorf** [comment]
> Linter fails on trailing whitespace here. Can you fix this and I'll /lgtm it?

@dulek But it says that the CSI test fails. But I am not working on the CSI here. Is it better to skip the test here?

**Comment by jichenjc** [comment]
I didn't see the CSI you mentioned ,can you help point the place? 

still seeing this error
```
rror: failed linting charts: failed processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ openstack-cloud-controller-manager => (version: "2.28.0-alpha.5", path: "charts/openstack-cloud-controller-manager") > failed waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
failed linting charts: failed processing charts
```

**Comment by simonostendorf** [comment]
> I didn't see the CSI you mentioned ,can you help point the place?

What I meant was the test commented by the bot. I didn't see the trailing spaces from the lint-ci, but it's fixed now.

**Comment by dulek** [comment]
I think Manila CSI tests are broken at the moment, we can override them if need be.

/retest

These issues are unrelated and caused by https://github.com/kubernetes/test-infra/issues/29622.

**Pull request merged**
