### PR TITLE
Add support for topology aware dynamic volume provisioning

### LINKED ISSUE #301: Add Features in Cinder CSI Driver
/kind feature

**What happened**:
With CSI v0.3.0 New Plugin Capabilties are added including Snapshot and Topology API, This features needs to be included in Cinder CSI driver.

Following CSI Interface are not implemented in cinder csi driver
 **Identity Service** 
 **Controller Service** 
    - ListVolumes, GetCapacity, ValidateVolumeCapabilities , ControllerGetCapabilities, CreateSnapshot, 
       DeleteSnapshot, ListSnapshots 
 **Node Service** 
    - NodeStageVolume , NodeUnstageVolume , NodeGetVolumeStats , NodeGetCapabilities

We need to check which interface we can implement, if not possible to implement we can atleast add them with default implementation.

https://github.com/container-storage-interface/spec/blob/master/spec.md

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
This PR implements following:

1. update metadata struct to return Availability zone information.
2. update NodeGetInfo function to return topology information eg. accessible_topology =
{"topology.cinder.csi.openstack.org/zone": "nova"}
2. consumes topology requirement if present in CreateVolume request and creates
volume using the given zone while favoring preferred topologies

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #301 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jichenjc** [comment]
@ramineni @adisky not direct relate to this patch but I think we need give a thought (maybe a follow up patch ?) is there any history reason do you know why csi/cinder/openstack/openstack_metadata.go only get metadata from metadata service and not include config drive? 
I know some cases metadata is not mandatory stuff but here csi use metadata service anyway

**Comment by ramineni** [comment]
>>  is there any history reason do you know why csi/cinder/openstack/openstack_metadata.go only get metadata from metadata service and not include config drive?
@jichenjc not sure about why it is not done. But I can see, cloud provider supports the same , we could utilize the same in csi also I suppose. I'll look into it and do it seperate patch.

**Comment by ramineni** [comment]
> @ramineni any question, I seems remember cinder/nova have their az respectively (not 100% sure), and the az info you got is from nova? but csi target to volume creation? will they align?

@jichenjc I have updated NodeGetInfo to retrieve the availability zone of the node only , which would be used by external provisoner . volumes topological requirement  could be specified in AllowedTopologies field of storage class, both would be considered while scheduling of pod.

**Comment by adisky** [comment]
@ramineni as discussed you want to add topology supoort after 1.0.0 update??

**Comment by adisky** [comment]
/hold 
till #470

**Comment by ramineni** [comment]
@adisky right, mainly because I need external-provisoner 1.01 release which has some bugs related to topology addressed which is inturn dependent on CSI 1.0 .

**Comment by ramineni** [comment]
@adisky updated with csi spec 1.0

**Comment by adisky** [comment]
/lgtm 
we can have a test in CI (provided kubernetes multi node cluster, and Openstack with atleast two az)

**Pull request merged**
