### PR TITLE
[release-1.28] [occm] ensure octavia monitor is always updated

### PR DESCRIPTION
**Pull request by kayrus**
This is a cherry-pick of #2373

```release-note
[occm] Ensure Octavia health monitors are updated on `UpdateLoadBalancer` k8s service controller call.
```

### CODE REVIEW

**Comment by dulek** [comment]
@kayrus Could you ping me on cherry-picks once the original patch merges?

**Comment by kayrus** [comment]
@jichenjc please approve

**Comment by kayrus** [comment]
@dulek @jichenjc please approve

**Pull request merged**
