### PR TITLE
[all] Add dulek and kayrus as approvers

### PR DESCRIPTION
**Pull request by mdbooth**
- Adds @dulek and @kayrus as approvers.
- Moves @chrigl and @ramineni to emeritus_approvers and removes them from reviewers.
- Removes @Fedosin from reviewers.

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
/approve

wait for a few days to unhold

**Comment by mdbooth** [comment]
> /approve
> 
> wait for a few days to unhold

I plan to assume a lazy consensus on Monday.

**Comment by dulek** [comment]
I just realized I cannot approve backports. Should be backport this? @jichenjc, @mdbooth, @zetaab?

**Comment by jichenjc** [comment]
yes, please cherry pick to older branch , thanks :)

**Pull request merged**
