### PR TITLE
Add full example for kubernetes.io/cinder provisioner

### LINKED ISSUE #62: Add full example for kubernetes.io/cinder provisioner
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Add full kubernetes.io/cinder provisioner example, make it easy for beginner to understand the difference with openstack.org/standalone-cinder provisioner.

**What you expected to happen**:
Understand kubernetes.io/cinder and openstack.org/standalone-cinder scenario.

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
NA

**Environment**:
NA

### PR DESCRIPTION
**Pull request by kiwik**
**What this PR does / why we need it**:
Add kubernetes.io/cinder example, make it easy for beginner to understand the difference with openstack.org/standalone-cinder provisioner.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
fixes #62

**Special notes for your reviewer**:
NA

**Release note**:
NA

### CODE REVIEW

**Comment by kiwik** [comment]
Have signed CLA.

**Comment by zetaab** [comment]
I am not fully sure is this really needed? We have similar example there already if people can combine two files

**Comment by kiwik** [comment]
@zetaab you mean "cinder-storage-class.yaml" and "example-pod.yaml"? looks there is no PVC define.

**Comment by zetaab** [comment]
https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/persistent-volume-provisioning/cinder/cinder-full.yaml https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/persistent-volume-provisioning/cinder/cinder-storage-class.yaml

**Comment by kiwik** [comment]
@zetaab I know your means, I just think if we can quick start a full stack example about kubernetes.io/cinder provisioner in one step "kubectl create -f cinder-in-tree-full.yaml", that is better for beginner than copying piece code from several files.

**Comment by dims** [comment]
+1 to full complete examples. please do update some doc too when you can that can explain the files.

/approve

**Comment by kfox1111** [comment]
Can we turn this, and some of the other yaml files into a helm chart? It would be great to be able to helm install the thing rather then tracking down all the individual bits, changing config, then uploading one by one.

**Comment by dims** [comment]
@kfox1111 +1 added a issue to track the idea

**Pull request merged**
