### PR TITLE
Update examples.md

### PR DESCRIPTION
**Pull request by lixin963**
provisoned  --> provisioned

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jichenjc** [comment]
please consolidate the typo fix so we can fix them in a batched mode, thanks~

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by jichenjc** [comment]
/hold 

I don't think we want to fix typo per PR as I mentioned in other PRs, please consider use tools to fix the typo in a batch
thanks for your help

**Comment by kayrus** [comment]
superseded by #2488

**Pull request closed without merging**
