### PR TITLE
[release-1.28] Remove duplicate pflag.Parse calls

### LINKED ISSUE #2464: [k8s-keystone-auth] Invalid args in keystone auth examples
The Example deployment for k8s-keystone-auth fails because of missing arguments in `provider-os/k8s-keystone-auth:v1.28.1`


https://github.com/kubernetes/cloud-provider-openstack/blob/fdba36babb2c4b46e759c99cca50ac7eba2ee06f/examples/webhook/keystone-deployment.yaml#L22-L31

Logs when the pod starts
```
2023/11/03 13:30:22 Running command:                                                                                                                                                                                                                                              
Command env: (log-file=, also-stdout=false, redirect-stderr=true)                                                                                                                                                                                                                 
Run from directory:                                                                                                                                                                                                                                                               
Executable path: ./bin/k8s-keystone-auth                                                                                                                                                                                                                                          
Args (comma-delimited): ./bin/k8s-keystone-auth,--tls-cert-file,/etc/pki/tls.crt,--tls-private-key-file,/etc/pki/tls.key,--policy-configmap-name,k8s-auth-policy,--keystone-url,http://10.246.154.17:5000/v3                                                                      
2023/11/03 13:30:22 Now listening for interrupts                                                                                                                                                                                                                                  
unknown flag: --tls-cert-file                                                                                                                                                                                                                                                     
Usage of ./bin/k8s-keystone-auth:                                                                                                                                                                                                                                                 
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)                                                                                                                                                                                 
      --user-agent stringArray         Extra data to add to gophercloud user-agent. Use multiple times to add more than one component.                                                                                                                                            
  -v, --v Level                        number for the log level verbosity                                                                                                                                                                                                         
      --version                        Show current version and exit                                                                                                                                                                                                              
      --vmodule moduleSpec             comma-separated list of pattern=N settings for file-filtered logging (only works for the default text log format)                                                                                                                          
unknown flag: --tls-cert-file                                                                                                                                                                                                                                                     
2023/11/03 13:30:22 running command: exit status 2                                                                                                                                                                                                                                
Stream closed EOF for kube-system/k8s-keystone-auth-5b99f99956-6qg7l (k8s-keystone-auth) 
```

### PR DESCRIPTION
**Pull request by stephenfin**
**What this PR does / why we need it**:

This is a partial backport of #2325, namely the fixes for issues introduced by #2324. This will fix #2464.

**Which issue this PR fixes(if applicable)**:

Fixes #2464

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stephenfin** [comment]
Note that the commits referenced don't actually exist on the remote and they only exist locally because garbage collector must not have run yet. Even with that caveat, I assume we still want to do things this way rather than cherry-pick the whole squashed change which includes feature'ish changes (the removal of glog handling code)?

**Comment by mdulko** [comment]
@stephenfin Hello, I think you tagged wrong person and you meant @dulek

**Comment by stephenfin** [comment]
@mdulko Indeed I did. Apologies! :smile:

**Comment by dulek** [comment]
Cheers @mdulko, I knew we'll meet one day. ;)

**Pull request merged**
