### PR TITLE
klog format error,follow kubernetes/kubernetes/pull/78250

### PR DESCRIPTION
**Pull request by qingsenLi**
**What this PR does / why we need it**:
ref#https://github.com/kubernetes/kubernetes/pull/78250
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
/lgtm

nice and clean :-)

**Comment by NickrenREN** [comment]
thanks @qingsenLi

**Pull request merged**
