### PR TITLE
Remove inactive reviewers/approvers  from OWNERS

### PR DESCRIPTION
**Pull request by adisky**
**What this PR does / why we need it**:
Remove inactive approvers/reviewers from OWNERS
https://github.com/kubernetes/kubernetes/issues/76269
used the script from @dims 
https://gist.github.com/dims/3261edf075660ad1bf5c338b8794c21b

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adisky** [comment]
@dims @hogepodge @lingxiankong @chrigl @ramineni If you are all fine with it we can remove inactive reviewers/approvers from OWNERS.

**Comment by lingxiankong** [comment]
I'm totally fine with this.

/lgtm

**Comment by dims** [comment]
/approve
/hold

please remove WIP when you feel ready and have pinged relevant folks.

**Comment by adisky** [comment]
pinged them on slack, waiting two weeks for reply,

**Comment by ricolin** [comment]
@adisky Ad matter of fact, I do plan to jump back to work on cloud-provider-openstack for the following months.
It will be nice if you can keep me in reviewer list, but totally understand if I'm removed for now.

**Comment by adisky** [comment]
@ricolin Thanks for reply, welcome back, will keep your name in reviewers list.

**Comment by ramineni** [comment]
please remove WIP if its final

**Pull request merged**
