### PR TITLE
New url for golint

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I33942bf37e03889c52a0215f39d1a4b5e264a7ff

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
thanks for the fix!

**Comment by dims** [comment]
This has `/lgtm` from @lingxiankong. merging it to unblock other PR(s) as this is a build break

**Pull request merged**
