### PR TITLE
[cinder-csi-plugin][charts] Remove snapshot controller yamls

### LINKED ISSUE #1698: [cinder-csi-plugin]Remove snapshot-controller related yaml from charts
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

https://github.com/kubernetes/cloud-provider-openstack/pull/1692#issuecomment-971179367

some discussion here related to helm charts of cinder-csi plugin snapshotter 

remove those seems a reasonable way to move

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
cinder-csi-plugin charts repo hosts snapshot-controller yamls , not CRDs which are required to be deployed along with them which might confuse the users more. As snapshot-controller should be deployed independent of csi driver and its cluster level, we dont need to host/maintain the charts in this repo. 

This PR is to remove the same from the repo. The documentation required to deploy the snapshot-controller is already in place pointing to the correct repo.https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#volume-snapshots

**Which issue this PR fixes(if applicable)**:
fixes #1698

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lingxiankong** [comment]
Can you look at the EasyCLA and see if it could be fixed?

**Comment by ramineni** [comment]
> Can you look at the EasyCLA and see if it could be fixed?

@lingxiankong EasyCLA is optional for kubernetes , https://github.com/kubernetes/test-infra/pull/24381 .

**Comment by ramineni** [comment]
@jichenjc PTAL

**Comment by jichenjc** [comment]
/approve

@ramineni do we need EasyCLA sign or it's false alert?

**Comment by ramineni** [comment]
> /approve
> 
> @ramineni do we need EasyCLA sign or it's false alert?

@jichenjc we dont need it , its ignored for kubernetes

**Pull request merged**
